### ISSUE TITLE
TODO: Rework Binders

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1072]
Rework Binders
===========

More about binders evidence here : https://github.com/The-Alpha-Project/alpha-core/issues/991

Thurgas
------------
https://db.thealphaproject.eu/index.php?action=show_creature&id=2813

Actually binder of Razor hill, we know that it is wrong for sure, he should be relocated to Hammerfall (arathi)
Entry range perfectly matches with Hammerfall

![](https://user-images.githubusercontent.com/72315006/226072445-d82e18d6-e121-4e1b-a6e3-ff715f598f1b.png)

- [ ] 2813 Thurgas should be relocated in Hammerfall

Teresa Shore
------------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=2815

If we except Baelish Frostbane that seems to be a test binder, there is no other human binder avalaible and we probably found them all.
Entry range also perfecly matches for Arathi

- [ ] 2815 Teresa shore should be spawned in Refuge Point (no ignored exisiting spawn)

Keldas
----------

https://db.thealphaproject.eu/index.php?action=show_creature&id=3306

This one was a mistery for long time.

He is actually a NE pet trainer, he should be changed to Orc binder.
We know that Pet Trainer NPCs should'nt exist in 0.5.3, Keldas has been reused

For evidence, all binders from starting zone have linked entries.
They also most of the time follow a logical order : starter zone binder -> town binder -> capital binder

Night Elf
![nebinder](https://user-images.githubusercontent.com/72315006/227946453-f3496777-3b90-414d-a912-9c6568fe8e2b.png)

Aldrassil (Aelyssa) -> Dolanaar (Myielea) -> Darnassus (Syurana)

Dwarf
![dwarfbinder](https://user-images.githubusercontent.com/72315006/227946462-ab32a78b-3b28-466f-b915-1d644aa23f1b.png)

Coldrige Valley (Bartok) -> Kharanos (Fulgar) -> Ironforge (Kerrik)

Orc
![keldas](https://user-images.githubusercontent.com/72315006/227946467-e165b293-9021-48b8-aed1-a0c9b4abc922.png)

Valley of Trials (Grisha) -> Razor Hill (Keldas) -> Orgrimmar (Orgrun Blackstuck)

Keldas is most likely binder of Razor Hill, it follows the exact same order as other starting zone binders.
It is possible than 0.5.3 name was not Keldas (Like Aethalas Cromwell, binder of Silverpine, reused as Battlemaster)

Since he doesnt have model, we could use standard orc, or display_id 240 used by orc binder test
![testbinder](https://user-images.githubusercontent.com/72315006/227946800-820edc94-8b91-46c1-9abf-66204f29f59e.png)

(As Baelish Frostbane, Orgrun Iceflow is probably a test binder that should be not spawned)

- [ ] 3306 Keldas should be relocated to Razor Hill
- [ ] Subname should be updated to "Binder"
- [ ] Flag should be updated to binder
- [ ] Display_id should be changed to 240

Aethalas Cromwell
------------------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=2302

We can see here 2 unused binders models,  the first is Aethalas Cromwell model
![Capture d’écran_2023-03-18_01-09-55](https://user-images.githubusercontent.com/72315006/227946586-ab2b05b1-f16b-4967-84ba-f3e6176e8358.png)

- [ ] 2302 Aethalas Cromwell should use display_id  3579

**Comment by geo-tp** [comment]
Lyranne May
------------------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=2303

![images_3925](https://user-images.githubusercontent.com/72315006/228058072-538b9bfb-16f0-4cf8-b3ce-ebaf904be148.jpg)

As we can see here, Lyranne use the second one. It makes sense, both entry and display_id are linked.

![Capture d’écran_2023-03-27_22-21-09](https://user-images.githubusercontent.com/72315006/228058671-37dd53b5-b22e-4829-8ace-89dba45396c2.png)


The model she is using actually make no sense, probably a random choice did long time ago, as we can see, it is part of a set male/female used by Forsaken Scoot
![Capture d’écran_2023-03-27_22-32-20](https://user-images.githubusercontent.com/72315006/228059680-e9c707b1-bea4-42d1-84cd-781137ccc76a.png)


- [ ] 2303 Lyranne May should use display_id 3580
