### ISSUE TITLE
TODO: Update last remaining unique display_id

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1089]
Update last remaining unique display_id
=====================

Partial https://github.com/The-Alpha-Project/alpha-core/issues/1044

5145 Juli Stormbraid Mage Trainer
--------------------
https://db.thealphaproject.eu/index.php?action=show_creature&id=5145

If we scroll through the entries looking at the set of display_id at the same time, we realize that she can only use this display_id, it's perfecly match.

![stmbrd](https://user-images.githubusercontent.com/72315006/228831740-2f066b10-58f5-45a9-925a-45157aed0d39.png)

Since dwarf mage will be canceled, no sense to have a dwarf mage trainer anymore.
That's why she has changed to gnome and that's why this display_id is unused.

- [ ] 5145 Juli Stormbraid should use display_id 3067
- [ ] She should be updated to dwarf faction

1321 Alyssa Griffith
--------------------
https://db.thealphaproject.eu/index.php?action=show_creature&id=1321

Alyssa uses a wrong display_id that is already used by another NPC, no idea why
She should use its final model same id as vanilla,  we already have it

https://www.wowhead.com/classic/fr/npc=1321/alyssa-griffith

- [ ] 1321 Alyssa should use display_id 1520

4959  Jorgen
-----------------
https://classicdb.ch/?npc=4959
https://db.thealphaproject.eu/index.php?action=show_creature&id=4959

See old model (0.5.3)
![jorgen](https://user-images.githubusercontent.com/72315006/228831852-1d1d6386-f1c7-4f22-98d4-cde707097c55.png)

See new model (1.12)
![jorgen2](https://user-images.githubusercontent.com/72315006/228831867-7001c11d-857e-494c-8a39-eca346abb03a.png)

See final model (1.12)
![jorgen3](https://user-images.githubusercontent.com/72315006/228831893-3a62d7a8-2562-4d00-8345-7160a768246b.png)

Weird that blizzard overwritted 2960 but finally use 4469 at release.

- [ ] 4959 Jorgen should use display_id 2960

4165 Elyissa Portal Trainer
----------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=4165

See old model (0.5.3)
![portaltr](https://user-images.githubusercontent.com/72315006/228831936-27f2d6f9-f9e4-4bad-8c88-ecf65a773f96.png)

See new model (1.12)
![portaltrainer](https://user-images.githubusercontent.com/72315006/228831953-ccc21cda-97ac-4ea5-8e2b-4a8a81127190.png)

See final model (1.12)
![prtl](https://user-images.githubusercontent.com/72315006/228831969-d969d523-25df-4c0b-bbf5-af4718fbeb9e.png)

Elyissa has been reused to Elissa Dumas human portal trainer

https://www.wowhead.com/classic/fr/npc=4165/elissa-dumas

- [ ] 4165 Elyissa should use  display_id 2204

4160 Ainethil Herbalism trianer
-------------------
https://db.thealphaproject.eu/index.php?action=show_creature&id=4160

trainers night elves use these models

![aet](https://user-images.githubusercontent.com/72315006/228832430-0f000064-fa33-48ee-bffc-aa1e2fda50d6.png)
![tann](https://user-images.githubusercontent.com/72315006/228832440-f4a735a8-960f-4787-b446-e06b9d3828ae.png)
![unusedelv](https://user-images.githubusercontent.com/72315006/228832464-28d42b49-2a78-421b-9ac0-1a34eec332f2.png)

Since Ainethil is the only NE trainer that miss display_id, it makes sense to use it
The range is also perfecly matching and it's the last unused female NE model

- [ ] 4160 Ainethil should use display_id 2215

3048 Ursyn Ghull
------------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=3048

See old model (0.5.3)
![ursynunused](https://user-images.githubusercontent.com/72315006/228832009-57ccf554-03b1-4847-a3b2-8b25e0d26d68.png)

See new model  (1.12)
![ursyn](https://user-images.githubusercontent.com/72315006/228832024-ad88ad9f-b488-49e2-922b-f6a778c564ad.png)

See final model (1.12)
![ursyn3](https://user-images.githubusercontent.com/72315006/228832042-88541472-da18-4cba-947a-7af5747740dd.png)

https://www.wowhead.com/classic/fr/npc=3048/ursyn-ghull

- [ ] 3048 Ursyn Ghull should use display_id 2136

5123 Bretta Goldfury
-------------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=5123

She should use unique model, same as vanilla and already present.
For some reasons, she use same model as Skolmin Goldfury (could be my bad this time)

https://www.wowhead.com/classic/fr/npc=5123/bretta-goldfury

- [ ] 5123 Bretta should use display_id 3058

Uthrar Threx Tailor Supplies
-------------------

(SEE COMMENT BELOW FOR THIS ONE)

https://db.thealphaproject.eu/index.php?action=show_creature&id=1703

This guy is actually unused, except display_id i cant find any infos about him
He should most likely stand at Ironforge with Tailor Trainer (linked display_id)

All tailoring NPC uses this kind of cloth and since it's linked with Tailor trainer, it's obvious.

![tailor3](https://user-images.githubusercontent.com/72315006/228832163-cc23b8f4-2bc3-44b7-91b2-3e4843cc02c9.png)
![tailor1](https://user-images.githubusercontent.com/72315006/228832212-837e3afc-8841-4647-bd12-beae8be7766f.png)
![tailor2](https://user-images.githubusercontent.com/72315006/228832233-612103ab-1dd2-48b0-aac3-15afb542cb87.png)

We dont even know if we will use it a day, but we should update display_id to prevent to use it on anything else.

- [ ]  1703 Ulthar Threx use display_id  3090

Should we spawn this guy ? If yes

- [ ] 1703 Ulthar Threx should be spawned near 5153 Jormund Stonebrow

Witherbark Shadow Hunter
-----------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=2557

For some reasons, this mob dont use display_id2 4000 as he should.
Vanilla does like that : 3999 & 4000, we only use the first one

- [ ] 2557 Witherbark Shadow Hunter should use display_id2 4000
(display_id1 is good, we need to update only display_id2)

3190 Rhinag
------------
https://db.thealphaproject.eu/index.php?action=show_creature&id=3190

He should use same display_id as vanilla, for some reason he doesnt

https://www.wowhead.com/classic/fr/npc=3190/rhinag

- [ ] 3190 Rhinag should use display_id  4075

1350 Theresa Moulaine
-----------------------

https://db.thealphaproject.eu/index.php?action=show_creature&id=1350

old model (0.5.3)
![robevendor](https://user-images.githubusercontent.com/72315006/228832301-73f3ba02-6ce6-4ff9-873f-727e7c117f86.png)

new model (1.12)
![robevendor2](https://user-images.githubusercontent.com/72315006/228832307-a75f3445-c639-40af-90b1-4147c8a9943f.png)

https://www.wowhead.com/classic/fr/npc=1350/theresa-moulaine

- [ ] 1350 Theresa should use display_id 1498 

657 Defias Pirate
----------
https://db.thealphaproject.eu/index.php?action=show_creature&id=657

Should use same as vanilla, actually it only uses male model.

https://www.wowhead.com/classic/fr/npc=657/pirate-d%C3%A9fias

- [ ] 657 Defias Pirate should use display_id2 2348
(display_id1 is good, we need to update only display_id2)

**Comment by geo-tp** [comment]
Did a mistake on Uthrar Threx Tailor Supplies.

Uthrar Threx Tailor Supplies
---------

No need anything for him, my logic was probably right, but they seems to reused this model for portal trainer


Belstaff Stormeye
----------

belstaff old
![tailor3](https://user-images.githubusercontent.com/72315006/228909627-66b3c07e-8a4c-44f7-a56d-52afddb1565e.png)


belstaff new
![Capture d’écran_2023-03-30_18-52-17](https://user-images.githubusercontent.com/72315006/228909643-03ae782f-6fa3-47ac-87af-014a519ef051.png)

Since dwarf mage will be removed, it was changed to gnome

2489 should use display_id 3090

**Comment by geo-tp** [comment]
![original_ss_1349](https://user-images.githubusercontent.com/72315006/229580283-52b80de8-5891-465b-84c1-7f3737eb0034.jpg)

screenshot confirmation for Portal/Mage trainer display_id

**Comment by geo-tp** [comment]
![Night-Elf-at-Fountain](https://user-images.githubusercontent.com/72315006/229864834-a993267d-f91f-49c7-93fb-a7815d399977.jpg)

screenshot confirmation for NE portal trainer display_id
