### ISSUE TITLE
TODO:  Spawn the last Binder

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1167]
**Describe what needs to be implemented or enhanced**

Tarren Mill is the last bindstone without a binder.

Kayren Soothallow
https://db.thealphaproject.eu/index.php?action=show_creature&id=2401

Alpha core location 
![kayren](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/fbfe94ec-2f58-4fbc-a812-21961b94b09f)

As we can see on ~0.5.3 screenshots, Kayren is not spawned.
![wow_undead_duel](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/74d9427e-3ffb-4230-ac9a-a2e97d8aa9ce)
![wow_undead_taren_mills](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/2cc93cf7-2c19-4e8f-85f7-94aca4f9cb66)

Since entry 2401 is low, most likely Kayren was reused or relocated. 
Display_id/Entry perfecly match with all others Tarren Mill NPCs around.
Its original spawn couldn't be anywhere else than Tarren Mill.

As we can see here with others female UD binders, clothes are barely the same.

![binders](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/1fb2d5f2-3879-4d9d-9bb9-1df4cc57cdab)
![kayrenmodel](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/d33be991-bb6a-4ff4-9ba9-1a1649d9de0c)

![226072284-209d010e-746a-4a0e-8ee5-75205cb0fb3d](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/a6c98ac0-519c-479f-9830-7cec5ab9d9f4)

We have a screenshot from 0.8+ where we can see Kayren at this location
![8 JULY 04 25](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/2135e4d8-2515-48ec-9247-d9a86f3ccf4f)

### Kayren should be Binder of Tarren Mill, she was reused as General Good later when Bindstone were removed.

- [ ] 2401 Kayren Soothallow should be moved next to Bindstone
- [ ] Subname should be updated to "Binder"
- [ ] Flag should be updated to binder flag
