### ISSUE TITLE
TODO: Enhance Durotar's Burning Blade chain by a removed quest.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1201]
At some point in development Blizzard decided, that trolls and orcs leaving Valley of Trials should immediately progress to Sen'Jin Village, instead of visiting Razor Hill, first. It impacted one chain in general, which needs to be returned back to 0.5.3 state.

- [ ] Swap Quest IDs of [Report to Sen'Jin Village](https://db.thealphaproject.eu/index.php?action=show_quest&id=805&filter=805&sort_order=Title&pos=1&max=1) and [Report to Orgnil](https://db.thealphaproject.eu/index.php?action=show_quest&id=823&filter=orgnil&sort_order=Title&pos=2&max=2) quests,

**Reasoning**
Firstly, [Report to Sen'Jin Village] quest shouldn't exist, in Alpha, but its ID after change will be used to bring back a removed quest (which had this ID), while simultaneously making [Report to Orgnil] quest's ID correct, It seems that it's the lowest amount of effort to make those things Alphalike

**Source**
Quest Database from 16/06/2004 (second day of patch 0.7)
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html

- [ ] Change characteristics of [Report to Orgnil](https://db.thealphaproject.eu/index.php?action=show_quest&id=823&filter=sen%27jin&sort_order=Title&pos=6&max=8) quest (which at this point should already have the correct ID of 805).

**Quest Details**
- It should have a QuestID of 805
- It should be offered by [Zureetha Fargaze](https://db.thealphaproject.eu/index.php?action=show_creature&id=3145) instead of [Master Gadrin](https://db.thealphaproject.eu/index.php?action=show_creature&id=3188&filter=master+gadrin&sort_order=name&pos=1&max=1)
- It should be offered after [Burning Blade Medallion](https://db.thealphaproject.eu/index.php?action=show_quest&id=794) (**which it already is**)
- Should be turned into [Orgnil Soulscar](https://db.thealphaproject.eu/index.php?action=show_creature&id=3142) (**which it already is**) and Orgnil should make a small speech after it's completion. (**which he already does, but it'll be shown in the source**)
- The level of this quest chould be changed to 5 (because it will be offered from Valley of Trials after the change)
- Change the quest experience reward to 440.
- Quest Description should be : 

 Your trials against the Burning Blade are finished...here in the Valley. But I want you to report your findings.

Go to the town Razor Hill and seek out Orgnil Soulscar. Razor Hill is east out of the valley, then north along the dry riverbed.

We must tell Orgnil of the Burning Blade, and that they have reached as far as the Valley of Trials.

Go, < name >, and be swift. I fear the evil found in the Burning Blade Coven is but the herald of a larger threat...

**The completion part of the text is not known, but there is a strong likelyhood it hasn't changed as it is only a short reaction to our Burning Blade invesigation. It fits**

**Sources**
Screenshot from patch 0.6 showing quests being taken in Valley of Trials after [Burning Blade Medallion[
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/images_6376.jpg | 7eefedaf07020000

Quest Description from 0.7 quest database
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html

Screenshot from early 0.6 showing exp rewards and Orgnil's small speach after turning the quest in.
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/561795-534914_20040426_009.jpg | fcc8c0c0c3038703

- [ ] Remake the lost [Master Gadrin] Quest.

**Quest Characteristics**
- It should have a QuestID of 823
- It should be lvl 7
- It should be offered by [Orgnil Soulscar](https://db.thealphaproject.eu/index.php?action=show_creature&id=3142) after the completion of [Report to Orgnil](https://db.thealphaproject.eu/index.php?action=show_quest&id=823).
- It should be turned in to [Master Gadrin](https://db.thealphaproject.eu/index.php?action=show_creature&id=3188)
- It should award 210 exp
- The objective should be "Speak with Master Gadrin in Sen'jin Village."
- The quest description should be:

News regarding the Burning Blade has me troubled. And I have reports from our troll allies at Sen'jin Village that other evils may be brewing in our lands. We must stamp these out! Our people did not endure and defeat the demon's curse to let it infect our new home!

I will investigate the Burning Blade. You go to Sen'jin Village to the south and speak with Gadrin. He will tell you of their troubles.

Help the trolls, then return to me.

**Sources**
Screenshot from early 0.6 showing this quest
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/561795-534914_20040426_009.jpg | fcc8c0c0c3038703

Quest Database from early 0.7
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html

Another Quest Database from late 0.9
https://web.archive.org/web/20040906103642/http://www.goblinworkshop.com/quests/master-gadrin.html

**Progression**
Just to be clear I'm going to write the quest progression of this chain in 1.12.1 (what we have now) and how it should be in 0.5.3

**1.12.1**
[Vile Familiars] (ID 792) -> [Burning Blade Medalion] (ID 794) -> Take [Report to Sen'Jin Village] (ID 805) -> **move to Sen'Jin** -> take [Report to Orgnil] (ID 823) -> **move to Razor Hill** -> finish [Report to Orgnil]

**How it should be in 0.5.3**
[Vile Familiars] (ID 792) -> [Burning Blade Medalion] (ID 794) -> Take [Report to Orgnil] (with ID changed to 805) -> **move to Razor Hill** -> take [Master Gadrin] (ID changed to 823) -> **move to Sen'Jin) -> finish [Master Gadrin]
