### ISSUE TITLE
TODO: Minor barrens oases chain rework

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1202]
The Lushwater and Stagnant oases weren't always inhabited by [Oasis Snapjaws](https://db.thealphaproject.eu/index.php?action=show_creature&id=3461). At least up to 0.5.5/0.6 they were threshadons called [Mud Thresh] Blizzard has probably changed them into turtles for the following reasons:
- hunters gained one more type of pet to tame in the area
- threshadons can't walk on land, so they could constntly bug/evade when went on shore

---
- [ ] Change [Oasis Snapjaws](https://db.thealphaproject.eu/index.php?action=show_creature&id=3461&filter=oasis&sort_order=name&pos=1&max=1) to [Mud Threshes]

**Reasoning**
The Entry of [Mud Thresh] isn't known, but:
- Both [Oasis Snapjaws] and [Mud threshes] were used only for this one quest, [Altered beings](https://db.thealphaproject.eu/index.php?action=show_quest&id=880)
- They both use the same abilities
- [Altered beings] quest items reused the same ID when the change from [Mud Threshes] to [Oasis Snapjaws] happened [(Mud Thresh Hide](https://db.thealphaproject.eu/index.php?action=show_item&id=5098) (ID 5098) --> [Altered Snapjaw Shell](https://www.wowhead.com/classic/item=5098/altered-snapjaw-shell) (ID 5098).

This makes it **highly likely**, that Mud Threshes were using the same entryID as oasis snapjaws later. Even if they didn't, Snapjaws shouldn't exist in 0.5.3 at this point, so this entry is free for the taking.

**Mob characteristics**
Mud Threshes should:
- have the name Mud Thresh
- have the DisplayID of 1752
- use the same abilities as oasis snapjaws ([sling dirt](https://db.thealphaproject.eu/index.php?action=show_spell&id=6530))
- be the same lvl as oasis snapjaws (the only screenshot where their lvl is seen is lvl 15 and the quest lvl didn't change between 0.7 and 1.12.1)
- should have "AQUATIC = 262144" flag, since all threshadons can't leave water and walk on land.

---
- [ ] Remove all land [Mud Thresh/Oasis Snapjaw] spawns.

**Reasoning**
Because of the aquatic flag all [Mud Thresh/Oasis Snapjaw] spawns, which are on land should be removed to prevent evade-bugging/crashing. Even the new text description states, that they were only underwater. 

---
- [ ] Change [Altered Beings](https://db.thealphaproject.eu/index.php?action=show_quest&id=880) characteristics.

We have a frankenstein quest, where the text talks about snapjaws but the objective links to the quest items from mud threshes.

Quest objective should be changed to:
`Bring 8 Mud Thresh Hides to Tonga Runetotem at the Crossroads.`

Quest description text should be changed to:

> Your findings are incredible, < name >. These oases hold properties that must come from an outside source. Or perhaps an inside one.
> 
> I want to know how these fissures are affecting the beasts who drink from the oases' water.
> 
> Hunt mud threshes under the waters of the Lushwater and Stagnant Oases. Bring me their hides so I may examine them.
>

- Quest reward should be changed to 7s 50c.

**Sources**
Database entry from the middle of path 0.7
https://web.archive.org/web/20040629154009/http://wow.warcraftstrategy.com/sg_quests.php?QuestId=880

Screenshot from 16/07/2004 (early 0.8)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/www_judgehype_com/Galerie%20d-images%20-%20Beta%20screenshots%20-%2016%20juin%202004%20-%20World%20of%20Warcraft%20-%20JudgeHype%20-%2004-09-2021%2004-45-35/16%20JULY%2004%20%20%2075.jpg | 173730000032777e

Screenshot from 20/04/2004 (early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/WoWScrnShot_042004_174429.jpg | 0339f8e0f878c644

**Comment by klorine28** [comment]
i have read the updates .sql and have an idea of how to do the issue my question is how do I know what ID number to use? I see that to make an update you have to start with this "if (select count(*) from `applied_updates` where id='250620231') = 0 then" and then make the changes and then close the if statement but what id do you have to use?

**Comment by GrenderG** [comment]
> i have read the updates .sql and have an idea of how to do the issue my question is how do I know what ID number to use? I see that to make an update you have to start with this "if (select count(*) from `applied_updates` where id='250620231') = 0 then" and then make the changes and then close the if statement but what id do you have to use?

Hi! That ID is: day/month/year + incremental number in case there are multiple updates in the same day.

**Comment by klorine28** [comment]
would the aquatic flag be an npc flag?
