### ISSUE TITLE
TODO: Rework the Raptor Thieves quest

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1203]
This quest worked a bit differently in alpha and early beta. Blizzard most likely changed it and reworked it into a small chain to add some variety than "kill stuff".

----
- [ ] Change [Raptor Thieves] quest's characteristics

[Raptor Thieves](https://db.thealphaproject.eu/index.php?action=show_quest&id=869&filter=raptor+thieves&sort_order=Title&pos=1&max=1) should:

- be changed to "Stolen Silver' As it was its original name
- require 15 [Raptor Heads](https://db.thealphaproject.eu/index.php?action=show_item&id=5062) instead of 12 and 4 pieces of [Stolen Silver](https://db.thealphaproject.eu/index.php?action=show_item&id=5061&filter=stolen+silver&sort_order=name&pos=1&max=1)
- award 4 silver instead of 6
- have a bit modified quest objective text
`Bring 15 Raptor Heads and 4 crates of Stolen Silver to Gazrog at the Crossroads.`
- have a bit modified quest description text

> Not` long ago, a shipment of silver was stolen from our guard tower. It was meant as payroll to the Crossroads' guards, and we want that silver back.
>
>The strange thing is...we caught one of the thieves on the night of the theft. And...it was a raptor! Unbelievable!
>
>I don't know what raptors would want with silver. But I don't care -- I want it back, and I want the raptors dead so they won't steal from us again!
>
>Search for raptors in the Barrens. Collect their heads, and find our stolen silver.

- have a bit modified completion text

> You found the silver! And what's more important, you got rid of the raptors!
>
> Thank you, [yourname]. You are a [class] of worth.

----
- [ ] Change [Stolen Silver] quest objective's characteristics

[Stolen Silver](https://db.thealphaproject.eu/index.php?action=show_item&id=5061&filter=stolen+silver&sort_order=name&pos=1&max=1), however, should:
- be stackable to 4 pieces only
- **DROP FROM RAPTORS** instead of going to their nest to loot it from a lockbox. 

After analysing the screenshot creator's lvling journey I have determined that he most likely killed 2 types of raptors ([Sunscale Lashtails](https://db.thealphaproject.eu/index.php?action=show_creature&id=3254&filter=sunscale&sort_order=name&pos=1&max=3) and [Sunscale Screechers](https://db.thealphaproject.eu/index.php?action=show_creature&id=3255&filter=sunscale&sort_order=name&pos=2&max=3)), however there one database states, that stolen silver could be dropped from [Sunscale Scytheclaws](https://db.thealphaproject.eu/index.php?action=show_creature&id=3256&filter=sunscale&sort_order=name&pos=3&max=3), so it would probably be a good idea to add [Stolen Silver] to all three raptors' loot tables. 

- Stolen Silver drop chance should be changed to about 8-15% (my estimation)

**Reasoning**
The only screenshot of these items being looted shows two pieces of [Stolen Silver] being dropped by two consecutive mobs. That means the chance of it high enough to be present on random screenshots and it should be low enough to be completable during the retrieval of the other quest objective - 15 [Raptor Heads]

----
- [ ] Remove [Sunscale Scytheclaw] spawns from their proto-nest.

**Reasoning**
The raptor isn't present in 0.5.3, but because of using sniffs from later patches server spawns raptors in the mountains.
The effect being:
![Raptors](https://github.com/The-Alpha-Project/alpha-core/assets/111394734/da9af005-5542-404e-85b1-a0f386bdbd02)

Most of raptors in the red area should be despawned, leaving one or two so that the plase doesn't look empty.
![map](https://github.com/The-Alpha-Project/alpha-core/assets/111394734/065d956b-0dfb-4ab1-80be-28720ceb5b31)

**Sources**
The only screenshot showing raptors dropping [Stolen Silver] (early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/www_judgehype_com/Galerie%20d-images%20-%20Beta%20screenshots%20-%2027%20avril%202004%20-%20World%20of%20Warcraft%20-%20JudgeHype%20-%2004-09-2021%2004-40-57/27%20APRIL%20%2004%20-%20174.jpg | 070300093f23077f

Database from 0.7 showing this quest's old name,. ID, quest text, silver reward and objectives
https://web.archive.org/web/20040822144619/http://wow.warcraftstrategy.com/sg_quests.php?QuestId=869

Database showing drops from Sunscale Scytheclaws
https://web.archive.org/web/20050213195805/http://www.goblinworkshop.com:80/items/stolen-silver.html

Database showing the original quest's completion text.
https://web.archive.org/web/20041016035100/http://goblinworkshop.com/quests/stolen-silver.html
