### ISSUE TITLE
TODO: The Grand Split and Rework of Sergra Darkthorn's quest chain.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1227]
Sergra's Shamanistic Chain
---
The vanilla version of Sergra Darkthorn's chiain is a merge of two separate quest chains present in 0.5.3. Sergra's part was more about helping the land and preserving the balance of nature, while Jorn Skyseer's one was about the hunt for great animals.
Changes need to be made to revert this chain back to 0.5.3 state.

- [x] [Plainstrider Menace](https://db.thealphaproject.eu/index.php?action=show_quest&id=844) rework

**To Do**
- Change currency reward to 4 silver and 5 copper.
- Change experience reward to 1200 exp.
- Change quest description text to:

> So you want to help, < name >? There are many things in the Barrens that need attention. However, before I turn your attention towards them, you should first learn a lesson.
>
> Yes, I think that is exactly what you need. The greater plainstriders to the east have been harassing some of our food supplies and have become a general nuisance.
>
> Put down the greater plainstriders and return to me seven of their beaks. With their numbers reduced, perhaps they will not look to our foodstores for their daily meal.

- Change quest completion text to:
>I feel the spirits of the Greater Plainstriders call out to me, can you not hear them? Ponder their deaths, [Name], for I sense that you do not truly understand what it is you have done.
>
>There will be a falling out because of your actions here today. You have no choice but to follow it through to the end now. Speak with me again, when you are ready.

**Sources**
Goblin Workshop database from 06/09/2004 (middle of patch 0.9)
https://web.archive.org/web/20040906103947/http://www.goblinworkshop.com:80/quests/plainstrider-menace.html

WarcraftStrategy from 16/06/2004 (second daty of 0.7)
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html

----

- [x] [The Zhevra](https://db.thealphaproject.eu/index.php?action=show_quest&id=845) Rework

**To Do**
- Change name to [Zhevra Dependence]
- Change currency reward to 4s 67c
- Change experience reward to 1300 exp.
- Change the quest description text to:

>There is an interdependency between the zhevra and the plainstriders. The plainstrider's constant scratching and pecking of the land actually tills the soil, allowing the plants that the zhevra eat to propogate.
>
>Without steady food, the zhevra have become agitated and encroach upon our field grains. Though your initial path was faulty, we must continue.
>
>Slay the zhevra runners to the north and bring me four zhevra hooves.

There is also this part `Keep the Hands of the New Moon, for they will grow as you learn. ` but it is a more difficult issue. There are 5 deprecated gloves "of the moon" in the database. Either it was an older version of the quest, where we upgraded them throughout this chain or it was simply a choice of different gloves for different classes. I wouldn't put that part in until we find more proof.

- Change quest completion text:

>With a good number of Zhevra Runners slaughtered, the orcish graints are safe again. I worry though what effect the deaths of so many Zhevra will have upon the beasts surrounding the Crossroads. Worry not, young one. The mystery of my teachings will become clear in time.

**Sources**
Goblin Workshop from 18/09/2004 (patch 0.10)
https://web.archive.org/web/20040918103749/http://www.goblinworkshop.com/quests/zhevra-dependence.html

WarcraftStrategy from 16/06/2004 (second day of 0.7)
https://web.archive.org/web/20050313194203/http://wow.warcraftstrategy.com/sg_quests.php?QuestId=845

Screenshot showing this quest existing on 27/04/2004 (early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/27%20APRIL%20%2004%20-%20173.jpg | ff3eb8800000c000

----

- [x] [Prowlers of the Barrens](https://db.thealphaproject.eu/index.php?action=show_quest&id=903&filter=prowlers&sort_order=Title&pos=2&max=4) rework

**To Do**
- change currency reward to 6s 7copper
- change the number of required [Prowler Claws](https://db.thealphaproject.eu/index.php?action=show_item&id=5096) to 10
- change quest objective text:

>Collect 10 Prowler Claws from Savannah Prowlers for Sergra Darkthorn in the Crossroads.

- change quest description text:

> It would seem our previous actions return to haunt us. WIth the Zhevra and Plainstrider game diminished, the Savannah Prowlers have turned upon our people as they use the southern road.
>
>Go south and collect 10 Prowler Claws and we just might reach an equilibrium again. 

- change quest progress text:

>Hurry, young one. The lives of those around the Crossroads are in your hands. Do you have the 10 Prowler Claws I requested? 

- change quest completion text:

>Well done, young one. Though the bloodshed here seems senseless, I can feel that the lessons of the Earthmother are close to your heart. There are few steps left to complete this circle, but soon you shall have the whole of the picture.

**Sources**
Warcraft Strategy (second day of 0.7)
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html

Goblin Workshop (captured at the time of 0.12)
https://web.archive.org/web/20041016031357/http://goblinworkshop.com:80/quests/prowlers-of-the-barrens.html

Official 0.5.5 patch notes, where the number of claws was reduced to 7
https://wowpedia.fandom.com/wiki/Patch_0.5.5

----

- [x] [The Angry Scytheclaws](https://db.thealphaproject.eu/index.php?action=show_quest&id=905&filter=the+angry&sort_order=Title&pos=1&max=1) rework

**To Do**
- change currency reward to 7s 65c
- change experience reward to 1700 

----

- [ ] [Enraged Thunder Lizards](https://db.thealphaproject.eu/index.php?action=show_quest&id=907) rework

**To Do**
- [Sergra Darkthorn](https://db.thealphaproject.eu/index.php?action=show_creature&id=3338&filter=sergra&sort_order=name&pos=1&max=1) should offer this quest in 0.5.3
- this quest should be turned in to Sergra aswell,
- change name to Enraged Stormsnouts
- change currency reward to 10s 70c
- change quest objective to:
>Collect 3 Stormsnout Blood Vials and return them to Sergra Darkthorn in the Crossroads.
- change quest description text to:
> The defilement of the scytheclaw nests has sent the stormsnout thunderlizards into a rage. It seems that they often picked through scytheclaw nests to consume the eggs. Without this... snack, they have begun trampling the life out of smaller creatures around them.
>
> You must slaughter the crazed beasts to the south and bring me three vials of their blood. The blood may prove useful later.
- **[SPECULATION]** I would also remove quest items from both [Stormhides](https://db.thealphaproject.eu/index.php?action=show_creature&id=3238) and [Thunderheads](https://db.thealphaproject.eu/index.php?action=show_creature&id=3239), as 1) The text is specifically calling for Stormsnout blood 2) the quest is saying, that only Stormsnouts are going crazy 3) The quest level is 18, the same lvl as Stormsnouts (18-19), but Stormhides and Thunderheads are higher (20-21 and 22-23 respectively) 4) Stormsnout is listed as the only mob capable of dropping it according to GoblinWorkshop.

**Source**
Screenshot from 0.5.5 showing, that this quest existed with that name
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/WoWScrnShot_041604_234253.jpg | fffefe0600000000

WarcraftStrategy (second day of 0.7)
https://web.archive.org/web/20040626182207/http://wow.warcraftstrategy.com/sg_quests.php?QuestId=907

----

- [ ] [Cry of the thunderhawk](https://db.thealphaproject.eu/index.php?action=show_quest&id=913&filter=cry&sort_order=Title&pos=7&max=30) rework

**To Do**
- [Sergra Darkthorn](https://db.thealphaproject.eu/index.php?action=show_creature&id=3338&filter=sergra&sort_order=name&pos=1&max=1) should offer this quest in 0.5.3
- this quest should be turned in to Sergra aswell,
- change name to Cry of the Cloudscraper
- change quest objective to:
>Something is disrupting the energies of my spell! The Earthmother is crying out, can you not hear it, [Name]?
>
> Earthmother! What is it that tears at your spirit?
>
> [Name], you must do as I say. Seek out the flying serpent Cloudscraper to the south, slay it and bring me its wings. Something dark has come upon the Barrens, and we are all at risk.
>
> Be swift, [class]. I do not know what atrocities it commits, but they must be of great magnitude to rile the spirits so.
- **[SPECULATION]** The quest objective, [Cloudscraper Wings](https://db.thealphaproject.eu/index.php?action=show_item&id=5164) should only be dropped by [Thunderhawk Cloudscraper](https://db.thealphaproject.eu/index.php?action=show_creature&id=3424), as 1) It is the only mob capable of dropping this item according to GoblinWorkshop 2) The quest specifies a Cloudscraper, not a generic thunderhawk. 3) The quest lvl is in accordance to the Cloudscraper's mob lvl. Greater Thunderhawks are too high and Hatchlings are a bit lower. 4) There are screenshots, where players ask in the barrens chat about cloudscrapers specifically.

**Source**
Screenshot with people asking about cloudscrapers (0.5.5)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/Escorting%20Blood%20Elf3.jpg | fffefcfc80804000

GoblinWorkshop (Captured on 16/10/2004)
https://web.archive.org/web/20041016021059/http://goblinworkshop.com:80/quests/cry-of-the-cloudscraper.html

----

- [ ] Rearrange the quest chain to reflect 0.5.3

According to Alakhazam the chain involving Sergra should look like this:
Plainstrider Menace (ID 844) --> Zhevra Dependence (845) --> Prowlers of the Barrens (903) --> The Angry Scytheclaws (905) --> Enraged Stormsnouts (907) --> Cry of the Cloudscraper (913)

**Source**
Alakhazam's quest listing
https://crawler.thealphaproject.eu/mnt/crawler/media/Website/wow.allakhazam.com/web.archive.org/web/20040804132746/http:/wow.allakhazam.com/db/qlookup.html%3Fzone=37.html

----
The hunt chain
---

- [x] [Echeyakee](https://db.thealphaproject.eu/index.php?action=show_quest&id=881) rework

**To Do**
- change experience reward to 2200
- change [Echeyakee](https://db.thealphaproject.eu/index.php?action=show_creature&id=3475)'s lvl to 17 (exact lvl isn't known, but we know, that his lvl was reduced to 16 in 0,5,5)

**Sources**
Screenshot from late 0.5.5/early 0.6
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/images_6682.jpg | 03c4fcccc3e10600

Official 0.5.5 patch notes reducing Echeyakee's lvl to 16
https://wowpedia.fandom.com/wiki/Patch_0.5.5

----

- [x] [Ishamuhale](https://db.thealphaproject.eu/index.php?action=show_quest&id=882&filter=ishamu&sort_order=Title&pos=1&max=1) rework

**To Do**
- change experience reward to 2300
- change quest description text to:
> Ishamuhale, Speartooth, is the fiercest sunscale raptor of the Barrens. He does not hunt for sport, nor for food. He hunts because hunting is his passion. He kills because it is his nature to kill.
>
>And you will learn of his nature, < name >, for your path now follows the taloned tracks of Ishamuhale.
>
>Begin the hunt. He roams to the east of the Crossroads, where his lesser brothers and sisters stalk their prey.
- spawn [Ishamuhale](https://db.thealphaproject.eu/index.php?action=show_creature&id=3257).
Alakhazam states, that before the rework Ishamuhale could spawn using **SOME OF** [Sunscale Scytheclaw](https://db.thealphaproject.eu/index.php?action=show_creature&id=3256&filter=sunscale&sort_order=name&pos=3&max=3) (and possibly [Sunscale Screecher](https://db.thealphaproject.eu/index.php?action=show_creature&id=3255&filter=sunscale&sort_order=name&pos=2&max=3)) spawnpoints, namely the 8-9 spawn points north-west of Ratchet. Screenshots from 0.5.5 seem to support this claim, as Ishamuhale's screenshot are taken in few different places about 300 yards apart. Either the spawnpoint theory is true or he had a really long patrol route.

**Source**
Allakhazam
https://web.archive.org/web/20040825142841/http://wow.allakhazam.com/db/quest.html?wquest=882

Screenshot from 0.5.5, north-eastern ridge
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/WoWScrnShot_050404_063836.jpg 0921f9fce7fcfe00

Screenshot from 0.5.5, south-western part
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/8%20MAY%20%2004%2030.jpg | ffff000000000000

----

- [ ] Rearrange the hunt chain to reflect 0.5.3

The Jorn Skyseer Hunt chain should look like this

Echeyakee (ID 881) --> Ishamuhale (882)

**[SPECULATION]** 
Even though I haven't found any proof supporting my claim, yet, I believe that this chain should be linked further with two other quests and look like this

Echeyakee (ID 881) --> Ishamuhale (882) --> Mahren Skyseer (874) --> Isha Awak (873)

**Reasoning**
1) Mahren Skyseer quest is also offered by Jorn Skyseer.
2) It mentions "continuing the hunt, having killed the beasts of barrens", signifying it most likely wasn't a chain starter.
2) The quests follow the same trend of hunting Tauren lore-connected mobs for glory/pride/strenght.
3) In vanilla they're linked to Jorn Skyseer,
