### ISSUE TITLE
TODO: Script Sarilus Foulborne

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1234]
- [ ] [Sarilus Foulborne](https://db.thealphaproject.eu/index.php?action=show_creature&id=3986&filter=foulborne&sort_order=name&pos=1&max=1) should use [Sarilus\'s Elementals](https://db.thealphaproject.eu/index.php?action=show_spell&id=6490&filter=element&sort_order=Name_enUS&pos=29&max=41) and Frostbolt spells.

**[Arbitration - Which frostbolt rank??]** 
The only screenshot we have is from 0.5.5 and shows Sarilus damaging the player for 137 dmg with his frostbolt. Since in 0.5.5 there was a general mage spell overhaul, resulting in a lot more ranks, it is impossible to use this rank in 0.5.3.

Here are the two options:
[Frostbolt (rank 2)](https://db.thealphaproject.eu/index.php?action=show_spell&id=205&filter=frostbolt&sort_order=Name_enUS&pos=2&max=13) - 90-96 dmg
[Frostbolt (rank 3)](https://db.thealphaproject.eu/index.php?action=show_spell&id=837&filter=frostbolt&sort_order=Name_enUS&pos=5&max=13) - 226-240 dmg

I believe rank 2 should be used in order for this NPC not to become a raidboss of 0.5.3. Most of classes at 25 would be killed with 3-4 frostbolts (rank 3) from this guy,

**[SPECULATION]**
There is also [Sarilus's Elementals Passive](https://db.thealphaproject.eu/index.php?action=show_spell&id=6488&filter=element&sort_order=Name_enUS&pos=30&max=41) spell, not sure what it does as I'm not that code-savvy. I'll describe how the fight should look like at the end of this report and the developer fixing it can see if it should be used.

----

- [ ] Change [Minor Water Guardian](https://db.thealphaproject.eu/index.php?action=show_creature&id=3950&filter=water+guardian&sort_order=name&pos=1&max=1)'s DisplayID

Elementals spawned by Sarilus should have an ID of either 110, 525 or 2069. The smaller the better.

----

- [ ] Connect [Minor Water Guardians](https://db.thealphaproject.eu/index.php?action=show_creature&id=3950&filter=guardian&sort_order=name&pos=4&max=10) to Feed Sarilus spells.

There are two spells, that, in my opinion, Minor Water Guardians should use:
[Feed Sarilus Passive](https://db.thealphaproject.eu/index.php?action=show_spell&id=6498&filter=sarilus&sort_order=Name_enUS&pos=2&max=4)
[Feed Sarilus Effect](https://db.thealphaproject.eu/index.php?action=show_spell&id=6497&filter=sarilus&sort_order=Name_enUS&pos=1&max=4)

Even though I can't understand from the spells' attributes how they should work, I've read about the fight and it should look like this.

Sarilius spawns Minor Water Guardians. If not Killed, they heal Sarilus.

**Source**
Official 0.5.5 patch notes mentioning more frequent mage spell ranks
https://wowpedia.fandom.com/wiki/Patch_0.5.5

Vanilla comments on WoWhead
https://www.wowhead.com/classic/npc=3986/sarilus-foulborne#comments

Screenshot from 0.5.5 showing Sarilus' elementals and frostbolt damage
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Barrens/normal_WoWScrnShot_032404_023223.jpg

**Comment by Fluglow** [comment]
Regarding the passive effects, it seems that both [Sarilus's Elementals Passive](https://db.thealphaproject.eu/index.php?action=show_spell&id=6488&filter=element&sort_order=Name_enUS&pos=30&max=41) (Hit chance + damage boost since they're level 1) and [Feed Sarilus Passive](https://db.thealphaproject.eu/index.php?action=show_spell&id=6498&filter=sarilus&sort_order=Name_enUS&pos=2&max=4) (periodic [Feed Sarilus Effect](https://db.thealphaproject.eu/index.php?action=show_spell&id=6497&filter=sarilus&sort_order=Name_enUS&pos=1&max=4) trigger) should be added as template auras for the elementals.
