### ISSUE TITLE
TODO: Pet trainers should spawn their respective pets

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1278]
**Describe what needs to be implemented or enhanced**

- [ ] Kyln longlaw currently spawn a bear, but he is BOAR trainer : https://db.thealphaproject.eu/index.php?action=show_creature&id=3697
- [ ] Dylan Bissel, spawn a wolf : https://db.thealphaproject.eu/index.php?action=show_creature&id=2942
- [ ] Grunenstur Balindom, spawn a crocilisk : https://db.thealphaproject.eu/index.php?action=show_creature&id=2876
- [ ] Harruk, spawn a crocolisk : https://db.thealphaproject.eu/index.php?action=show_creature&id=3620
- [ ]  Jadenvis Seewatcher, spawn a crab : https://db.thealphaproject.eu/index.php?action=show_creature&id=3700
