### ISSUE TITLE
TODO: Four-Legged Meneces Quest Completion

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1318]
Found more information about this quest. Now we have all of the NPC Quest Text.

- [ ] Fill the quest completion text to:

>Excellent. Your assistance to the people of Duskwood will not be forgotten. Here, a token of my appreciation.

- [ ] Change the currency reward to 8 silver

- [ ] Change the experience reward to 1500

[SPECULATION] - The experience reward is estimated by me judging from similar, easy quests at this lvl range. Currently this quest gives almost 4k experience, which is almost twice the amount people get for doing [Mor'Ladim](https://db.thealphaproject.eu/index.php?action=show_quest&id=228&filter=mor%27ladim&sort_order=Title&pos=1&max=2), an elite quest involving more than one person. I assume this quest should give no less than 1200 and 2000 experience, so 1500 should be a balanced reward for killing 12 wolves in the forest.

**Sources**
Goblin Workshop captured at 24/06 (middle of 0.7)
https://web.archive.org/web/20040624232921/http://www.goblinworkshop.com/quests/four-legged-menaces.html

WarcraftStrategy from 16/06 (second day of 0.7)
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html
