### ISSUE TITLE
TODO: Durotar Mobs's Abilities

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1347]
Some info for future reference
- Most likely all Scytheclaws use Rushing Charge
- Most likely all Scorpids use some Poison variant
- Most likely all Quilboars use Razor Mane
However there aren't any screenshots of them, yet.

It is safe to say, though, that after this fix a vast majority of NPC skills in Durotar will be blizzlike.

- [ ] [Scorpid Workers](https://db.thealphaproject.eu/index.php?action=show_creature&id=3124&filter=scorpid&sort_order=name&pos=9&max=13) should use [Weak Poison](https://db.thealphaproject.eu/index.php?action=show_spell&id=6751&filter=weak+poison&sort_order=Name_enUS&pos=1&max=2)
Source
[0.5.4](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/janvier2004-47.jpg) | 7efb410033333600

- [ ] [Clattering Scorpids](https://db.thealphaproject.eu/index.php?action=show_creature&id=3125&filter=scorpid&sort_order=name&pos=2&max=13) should use [Poison](https://db.thealphaproject.eu/index.php?action=show_spell&id=744&filter=poison&sort_order=Name_enUS&pos=41&max=85)
Source
[0.5.4](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/748.jpg) | 6c177fffc300c600

- [ ] [Venomtail Scorpids](https://db.thealphaproject.eu/index.php?action=show_creature&id=3127&filter=scorpid&sort_order=name&pos=11&max=13) should use [Venom Sting](https://db.thealphaproject.eu/index.php?action=show_spell&id=5416&filter=venom&sort_order=Name_enUS&pos=6&max=8)
Source
[0.6](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/images_6617.jpg) | fff8c99fa7f30200

- [ ] [Dire Mottled Boars](https://db.thealphaproject.eu/index.php?action=show_creature&id=3099&filter=dire+mottled&sort_order=name&pos=1&max=1) should use [Boar Charge](https://db.thealphaproject.eu/index.php?action=show_spell&id=3385&filter=boar+charge&sort_order=Name_enUS&pos=1&max=1)
Their DisplayID should also be different (DisplayID of 503 - the same of regular Mottled Boars would suffice if there are no slightly larger models. The other similar are 193, 389, 454, 463, 499, 1167, 1168, 1169, 1242)
Source
[0.6](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/worldofwarcrafthorde_041504_012.jpg) | 7cfefe8400206602

- [ ] [Bloodtalon Scythemaws](https://db.thealphaproject.eu/index.php?action=show_creature&id=3123&filter=bloodtalon&sort_order=name&pos=1&max=3) should use [Rushing Charge](https://db.thealphaproject.eu/index.php?action=show_spell&id=6268&filter=rushing&sort_order=Name_enUS&pos=2&max=10)
Source
[0.9](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/post-3-1093101556.jpg)

- [ ] [Razormane Dustrunners](https://db.thealphaproject.eu/index.php?action=show_creature&id=3113&filter=razormane&sort_order=name&pos=3&max=15) should use [Rejuvenation](https://db.thealphaproject.eu/index.php?action=show_spell&id=774&filter=rejuvenation&sort_order=Name_enUS&pos=3&max=31)
Source
[0.6](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/shyso_4.20_19.jpg) | fefe7f0000000000

- [ ] [Lieutenant Benedict](https://db.thealphaproject.eu/index.php?action=show_creature&id=3192&filter=benedict&sort_order=name&pos=1&max=2) should use [Improved Blocking], however there are 5 Improved Blocking spells. Need a Dev to decipher their differences.
[Kul Tiras Marines](https://db.thealphaproject.eu/index.php?action=show_creature&id=3129&filter=kul+tiras&sort_order=name&pos=1&max=2) should use Defe...(nsive stance?) A lot of mobs in the area use it at that lvl.
[Kul Tiras Sailors](https://db.thealphaproject.eu/index.php?action=show_creature&id=3128&filter=kul+tiras&sort_order=name&pos=2&max=2) should use [Rushing Charge](https://db.thealphaproject.eu/index.php?action=show_spell&id=6268&filter=rushing&sort_order=Name_enUS&pos=2&max=10)
Sources
[0.6](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/30%20APRIL%2004%2006.jpg) | 3f027f1f3f6e4600
[0.6](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/wowa_041504_019_1082075398-805895.jpg) | 010117034313fedf

- [ ] [Voodoo Trolls](https://db.thealphaproject.eu/index.php?action=show_creature&id=3206&filter=voodoo&sort_order=name&pos=1&max=1) should use [Shrink](https://db.thealphaproject.eu/index.php?action=show_spell&id=7289&filter=Shrink&sort_order=Name_enUS&pos=1&max=1) and [Lightning Shield](https://db.thealphaproject.eu/index.php?action=show_spell&id=324&filter=lightning+shield&sort_order=Name_enUS&pos=1&max=13)
[Hexed](https://db.thealphaproject.eu/index.php?action=show_creature&id=3207&filter=troll&sort_order=name&pos=4&max=11) Trolls should use [Immolate](https://db.thealphaproject.eu/index.php?action=show_spell&id=348&filter=immolate&sort_order=Name_enUS&pos=1&max=13). For some reason they are using rank 3, which will obliterate absolutely anybody, who doesn't one-shot them.
Source
[0.6 - Voodoo Trolls](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/images_6578.jpg) | 010167ff6fe30707
[0.12 - Hexed Trolls](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/21%20OCT%2004%20%20%20MMM05.jpg) | 030188cfa3e3f7bc

- [ ] [Burning Blade Cultists](https://db.thealphaproject.eu/index.php?action=show_creature&id=3199&filter=Burning+blade&sort_order=name&pos=7&max=15) should use [Immolate (rank 1)](https://db.thealphaproject.eu/index.php?action=show_spell&id=348&filter=immolate&sort_order=Name_enUS&pos=1&max=13). Same story as with Hexed Trolls.
Source
[0.6](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/images_6772.jpg) | 8341c29ef3ef8fef

**Comment by devw4r** [comment]
Most of this stuff is related to missing handlers for creature ai events except for the last two entries regarding Immolate and Shrink.
