### ISSUE TITLE
TODO: Rework Talents (stage 2)

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1362]
This time, apart from decluttering the talent page, some optimization in order to prevent abuse and gradually prepare the characters for the lowering of creatures’ damage in the future.

Bear in mind, however, that it’s the maximum blizzlike information we can squeeze from the current screenshots that we have (or rather have tagged) in the Alpha Archive. There’s also some speculation from my side, but it still does follow a pattern and is somewhat believable. 

----

Attribute Enhancement

- [ ] Adjust the talent point cost of attributes.

The talent cost of: Cat's Agility, Great Stamina, Heroic Strength, Indomitable Spirit, Mighty Intellect should start at 10 talent points and increase every 3 ranks.

[Rank 3 (0.5.5) - 10 TP](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Teldrassil/wowbeta_0043.jpg)
[Rank 4 (0.5.5) - 15 TP](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/WoWScrnShot_032404_193449.jpg)
[Rank 5 (0.5.5) - 15 TP](https://crawler.thealphaproject.eu/search/great%20stamina)
[Rank 6 (0.5.5) - 15 TP](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Redridge%20Mountains/8%20APRIL%20%2004%2019.jpg)
[Rank 7 (0.5.3) - 20 TP](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/gencon16.jpg)

----
Weapon Talents

- [ ] Adjust talent point cost of specializations

First rank of any specialization (both weapon and spell) costs 10 TP
Second 10 TP
Sixth 20 TP

[Rank 1 (0.5.5)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/screenhot_betatest_quest4.jpg) | c3e300000000f6ff
[Rank 2 (0.6)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/w6.jpeg) | 210001081cbcfcfe
[Rank 6 (0.5.3)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Westfall/gencon29.jpg)

It’s safe to assume that the cost of ranks increases by 5 TP per two ranks.
[r1-2 = 10TP / r3-4 = 15 TP / r5-6 = 20TP]

- [ ] Implement level requirements for specialization talents

First rank of any (weapon or spell) specialization is available at lvl 1
Second at lvl 5
sixth at lvl 25

It is safe to assume that the level requirement increases by 5 levels per rank.
[r1 = 0 / r2 = 5 / r3 = 10 / r4 = 15 / r5 = 20 / r6 = 25] 

[Rank 1 (0.5.5)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Dun%20Morogh/WoWScrnShot_031804_233102.jpg)
[Rank 2 (0.6)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Durotar/w6.jpeg)
[Rank 6 (0.5.3)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Westfall/gencon29.jpg)

- [ ] Implement requirements to (weapon/magic) Power talents

Any (Weapon) Power talent (Rank 1) should require:
- (This weapon) Specialization (rank 4)
- Physical Prowess (Rank 1)

There aren’t any screenshots with characters having (Magic) Power, but it’s safe to assume that the pattern is similar:
- (This Magic) Specialization (Rank 4)
- Mental Acuity (Rank 1) - Which is the caster equivalent of Physical Prowess.

[Rank 1 (0.5.5)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Dun%20Morogh/WoWScrnShot_031804_233101.jpg)

----

Defensive and Magic Talents

- [ ] Adjust the level requirement to the defensive talents

At lvl 1 the only defensive talent available should be Lightning Reflexes
[Paladin (0.5.5)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/screenhot_betatest_quest4.jpg)
[Mage (0.5.5)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/0320wow01.jpg)

Most defensive talents such as:
- Perceptive
- Regeneration
- Shield Defense (if a character can wear shields of bucklers)
- Sneaky (for druids and rogues)
- Toughness (everybody)
should become available at lvl 5  ([0.5.5](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/0416wow01.jpg))
And most likely should require 5 more levels for every new rank ([Toughness R5 (0.5.5)](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/www3_telus_net/www3_telus_netPush_1_-_Dwarf_Warrior_KyanMehwulfe_Lv25_04-01.jpg))

There’s a similar pattern with [Magic Talents]
At lvl 1 the only magic talents available should be (Magic) specialization talents. [0.5.5](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Dun%20Morogh/image0023.jpg)

Most magic talents such as:
- Meditation
- (School) Resist
should become at lvl 5 and most likely get a new rank every 5 lvls.
[Rogue lvl 2](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Teldrassil/ds008.jpg) - Notice no [Magic Talents] tab before [Slayer Talents], they are in alph order.
[Rogue lvl 5](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/0416wow01.jpg)

----
Slayer Talents

Beast Slayer and Undead Slayer should be the only available talents for new characters.

[0.5.5 mage](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Dun%20Morogh/image0023.jpg) | 39181c1f101cffff
[0.5.5 paladin](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/screenhot_betatest_quest4.jpg) | c3e300000000f6ff

Elemental Slayer can also be unlocked at some point during leveling. Judging from the talent cost and the fact that there aren’t a lot of elementals at earlier levels I’d suggest that Ele Slayer should be available at either lvl 20 or 25.

[LvL 25 Paladin](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Dun%20Morogh/wow_090.jpg) | ff80a0e0f1e080bf
