### ISSUE TITLE
TODO: Deadmines Boss Rework

### ISSUE THREAD

**Issue by VictoriumWoW** [The-Alpha-Project/alpha-core#1430]
### Rhahk'zor
- [x] Should not yell "VanCleef pay big for your heads!" on aggro.
- [x] Should be level 20 instead of level 19.
~~Should use a stone tomahawk instead of a hammer (seems to have wielded his hammer in Source 4 which is a "green bug" screenshot, but judging by the bag icon that isn't in 0.5.3 and the slightly yellow character portrait lines it was likely not 0.5.3.)~~
**Sources:**
1. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/WoWScrnShot_032404_203643.jpg
2. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/WOW_screenshots_350.jpg
3. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/dun3.jpg
4. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/47920517.jpg
5. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/dun3.jpg
6. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/WOW_screenshots_350.jpg
### Sneed's Shredder & Sneed
- [x] Shredder _may have been_ slightly taller.
- [x] Sneed should be level 21.
**Sources:**
1. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/ShieldBlock.jpg
2. https://crawler.thealphaproject.eu/mnt/crawler/media/Database/Allakhazam/creatures-details-2004.txt
### Gilnid
- [x] Should be taller, around double the height of the goblins around him. 
**Source:**
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/ShieldBlock2.jpg
### Mr. Smite
- [x] Should be level 21 instead of level 20.
- [x] Should say "Haha! You are proving to be a tough challenge. Guess I'll have to get a little more serious!" instead of "You land lubbers are tougher than I thought! I'll have to improvise!" when one third of his health is gone, and he should not say "Dah! Now you're making me angry!" and stun the group when two thirds of his health is gone.
- [x] The chest where he switches weapons should not appear.
- [x] Should not yell "We're under attack! A vast, ye swabs! Repel the invaders!" on aggro.
- [x] Appears to have used a two-handed sword with a black hilt and white blade and crossguard at the start of the battle, then switched to his cutlass at one-third of his health when he stuns the group. Because his chest isn't present, he seems to have done either a use emote (like when a player opens a container) or an applaud emote, then the cutlass would've replaced the two-handed sword, and then the stun would be removed from the party and he would re-engage combat (basically the same as the event that plays when he switches weapons at the chest on 1.12, except here he plays a different emote and switches on the spot.)
**Sources:**
1. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/05-05-04%204th%20Deadmines%20Boss%20(Mr.%20Smite).jpg
2. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/5-21_1_byjzzodo_l_1.jpg
3. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/MrSmite.jpg
4. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/normal_WoWScrnShot_040304_005708.jpg
5. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/05-05-04%204th%20Deadmines%20Boss%20(Mr.%20Smite%20Clean%20Pic).jpg
6. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/MrSmite.jpg
### Captain Greenskin
- [x] Should be level 21 instead of level 20.
- [x] Should be larger, probably the same model as Gilnid. Sneed may have also used this model.
- [x] Should run away in fear when on low health (presumably the same one NPCs like low level gnolls use.)
**Sources:**
1. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/deadmines19.jpg
2. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/tscullypics_WoWoW15.jpg
### Edwin VanCleef
- [x] Should not yell "None may challenge the Brotherhood!" on aggro.
- [x] Should be level 22 instead of level 21.
- [x] Should emote "calls more of his allies out of the shadows." when summoning Blackguards instead of yelling lines.
Sources:
1. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/05-05-04%20Final%20Deadmines%20Boss%20(Van%20Clef).jpg
2. https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/tscullypics_WoWoW18.jpg

**Comment by GrenderG** [comment]
About

> Should use a stone tomahawk instead of a hammer 

The screenshots where he appears using a tomahawk are way older than 0.5.3, 4th image shows him already using the hammer and this is before 0.5.3 too, so it's safe to assume in 0.5.3 he was using the hammer.

About some bosses not yelling on aggro. Are you 100% sure about it? It could be already hidden in the chat logs when the screenshot was taken.

**Comment by VictoriumWoW** [comment]
> About some bosses not yelling on aggro. Are you 100% sure about it? It could be already hidden in the chat logs when the screenshot was taken.

On going back and analyzing my sources for the bosses that have dialogue in the current version of Alpha Project, I feel fairly confident in the info I provided in the post (remove some lines, change others, etc.) Starting with Rhahk'zor, [Source 1](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/WoWScrnShot_032404_203643.jpg) and [Source 6](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/WOW_screenshots_350.jpg) show Rhahk'zor in the beginning/early stages of the fight. In 1, looking at the chat log, it appears that they had just pulled Rhahk'zor after discussing the strategy, with Rhahk'zor himself at basically full health. In 6, which in fairness is an earlier version than 0.5, Rhahk'zor is only slightly injured and his line isn't present, although it's possible that his line may have been drowned out by the skill increases so let's analyze 1 instead. 

In the shot, the warlock says he'll pull by casting a spell and dragging Rhahk'zor out, with one of the party members telling the warlock to do so when "next time he comes far out" (implying that Rhahk'zor had his mini patrol present in-game at the time of this shot), and we see Rhahk'zor attacking the voidwalker. Looking at the combat logs, it's clear that the warlock was relatively close to Rhahk'zor as he casted Corruption (which was resisted) and the voidwalker casted Torment a few times, likely to get Rhahk'zor off of the warlock. After entering the hallway, the party attacks Rhahk'zor.

For a timeline to put things into perspective: Warlock and party member discuss pull strategy > Warlock pulls Rhahk'zor > Rhahk'zor enters hallway > Party engages Rhahk'zor 

Remember that Rhahk'zor's line is yelled, meaning that players from far away can see it in the chat log. According to the timeline, the warlock was nearby Rhahk'zor, meaning it surely would've been seen by him, but in the screenshot it isn't present. So, assuming the things the party said were said according to the timeline provided, it's clear that Rhahk'zor had no dialogue as of at least version 0.6, and because 0.5.3 is older it's safe to assume that Rhahk'zor had no dialogue in 0.5.3 either.

As for Mr. Smite and Edwin VanCleef, Mr. Smite is much easier to judge as not only does he not yell his "We're under attack" line when pulled in 1.12 (he says it shortly after the door to the cove is blasted open) and says nothing when aggro'd, but [Source 2](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/5-21_1_byjzzodo_l_1.jpg) essentially confirms it was like this in 0.5.3 as well, as the emotes from his two Blackguards, which always pull alongside him, can be seen without any lines from Mr. Smite, and since the player who took the shot needed to be close to see the emotes, we can safely saw that Mr. Smite did not say anything when pulled in this older version or 0.5.3. The same logic applies for VanCleef and his Blackguards that pull with him, as can be seen in [Source 2](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/tscullypics_WoWoW18.jpg).

**Comment by geo-tp** [comment]
I didn't see that there was a solution for this, here are some more adjustements to do : 


- [ ] Defias Miner to Elite : https://db.thealphaproject.eu/index.php?action=show_creature&id=598
![9-8_3_otpopoms_l_1](https://github.com/user-attachments/assets/49bcf8ca-7748-46de-9432-a65b4a5b304a)

- [ ] Defias Worker to Elite : https://db.thealphaproject.eu/index.php?action=show_creature&id=1727
![Deadmines](https://github.com/user-attachments/assets/fb9cde8f-c1de-419a-989c-71f43346189a)

- [ ] Defias Strip Miner to Elite : https://db.thealphaproject.eu/index.php?action=show_creature&id=4416
![images_deadmines_18](https://github.com/user-attachments/assets/0a83b52c-b7be-496e-b3ec-9a70d51cfccd)

**Comment by GrenderG** [comment]
Regarding https://github.com/The-Alpha-Project/alpha-core/pull/1453 I see that **Defias Miner**, **Defias Strip Miner** and **Defias Worker** have been made elite mobs; however their health and damage has not been changed. They should be increased too to match elite values (I guess we can take the values of other humanoid elite mobs around their level).
