### ISSUE TITLE
TODO: Rework the "Down the Scarlet Path" questline

### ISSUE THREAD

**Issue by VictoriumWoW** [The-Alpha-Project/alpha-core#1438]
**Quest 1: Down the Scarlet Path (ID 261)**

- [x] In the Description, the text "It must be stopped before it overwhelms us and drags our world into shadow." should be changed to "It must be stopped before it washes over our last bastions and drags our world into shadow.", and the text "If you are with us, then gather your courage and prove your allegiance--destroy the undead ravagers of Desolace, in the Valley of Bones to the south." should be changed to "If you would take this same oath, then gather your courage and prove your allegiance - wage war with the Undead of Duskwood, and return to me with proof of your deeds.". Also, the text in Objectives should be changed from "Destroy 30 Undead Ravagers, then return to Brother Anton at Nijel's Point." to "Bring 12 Shriveled Eyes to Brother Anton in Stormwind." (https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Stormwind/images_5797.jpg).
- [x] The money reward should be changed to 20 Silver and the XP reward should be changed to 2050 (https://web.archive.org/web/20040822081145/http://www.goblinworkshop.com:80/quests/down-the-scarlet-path.html).
- [x] The quest level should be changed to 28 (https://web.archive.org/web/20040706015240/http://wow.allakhazam.com:80/db/quest.html?wquest=261) and the level requirement should be changed to either 23, which is in-line with the release quest's requirement which was its quest level (39) subtracted by 5 (34), or 18, given that the level requirements for many quests in the current database are often the quest level subtracted by 10. Regardless, period sources show that this quest was available at level 25 (https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Stormwind/images_5798.jpg).
- [x] The quest objective should be changed from 30 Undead Ravagers (which do not exist in the current database) to 12 Shriveled Eyes (ID 2477).
- [x] The zone should be changed to Duskwood (ID 10).

**Quest 2: Down the Scarlet Path (ID 1502)**

- [x] In the Description, the text "You have proven yourself against the undead in Desolace. But the true threat of the plague lies in Lordaeron." should be changed to "You have proven yourself against the undead in southern Azeroth. But the true threat of the plague lies in the northern lands of Lordaeron." (https://web.archive.org/web/20040903231516/http://www.goblinworkshop.com:80/quests/down-the-scarlet-path-2.html).
- [x] The quest level and level requirement should be the same as the previous quest (https://web.archive.org/web/20040705094556/http://wow.allakhazam.com:80/db/quest.html?wquest=1052).
- [x] The zone should be changed to Duskwood (ID 10)
- [x] The XP reward should be changed to 1200.

**Quest 3: In the Name of the Light (ID 1053)**

- [x] The quest level is 40 in both beta and release (https://web.archive.org/web/20040711112739/http://wow.allakhazam.com/db/quest.html?wquest=1053), the same level as Herod. However, with the Scarlet Monastery re-work and Herod's level reduced to 35, alongside no NPCs higher than 37 existing in the instance, the quest level should be changed to 35.
- [x] The zone should be changed to the alpha Monastery's ID (still under investigation.)
- [x] The level requirement should be the same as the previous quest.
- [x] The XP reward should be changed to 8650 (https://web.archive.org/web/20040906104143/http://goblinworkshop.com/quests/in-the-name-of-the-light.html).
- [x] The quest's weapon rewards have IDs in the 6800 range, which may not have existed in 0.5.3. Until we can find evidence that items in this range could've existed in 0.5.3, the quest shouldn't reward anything or should reward the Unknown Reward item (ID 1217).

**Quest NPCs**

- [x] Brother Anton (ID 1182) currently has an item equipped that couldn't have existed in 0.5.3 due to a high ID (12591). Period sources show that he had nothing equipped as early as 0.6. As such, his "equipment_id" value should be changed to 0. He should also be level 50 according to the same sources.
- [x] Raleigh the Devout (ID 3980) has a similar issue to Brother Anton in regards to equipped items, but I was unable to find any period sources of Raleigh, so I was unable to determine what he had equipped (if anything.) After the quest Down the Scarlet Path (ID 1502) is complete, the following event should play: https://youtu.be/Rm_DKLA7_hQ?t=307.

**Quest Items**

- [x] Ravager's Skull (ID 2477) should be renamed to "Shriveled Eye" and should have a medium-high drop chance from Brain Eaters (ID 570) and Plague Spreaders (ID 604).(https://web.archive.org/web/20041014172305/http://goblinworkshop.com/items/shriveled-eye.html). It may have also dropped from Bone Chewers (ID 210), and perhaps, albeit more unlikely, Fetid Corpses (ID 127) and Rotted Ones (ID 948) (https://web.archive.org/web/20050117182508/http://wow.allakhazam.com:80/db/item.html?witem=2477).

**Comment by VictoriumWoW** [comment]
Very nice work, this fixes almost every issue related to the questline and its items and NPCs. My only suggestion would be to change the level requirement of In the Name of the Light to 23, since if we look at similar questlines in Alpha such as the Battle of Hillsbrad, Elixir of Agony, A Dark Threat Looms, etc, we can see that while the quest levels change, the level requirements are always the same as the first quest in the chain. I would put this on hold though until we find/create a suitable zone ID for the alpha Monastery map which we can give to the quest.
