### ISSUE TITLE
TODO: Adjust Tharil'zun quest

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1452]
[Tharil'zun](https://db.thealphaproject.eu/index.php?action=show_quest&id=19) originaly had a second objective. Apart from killing the orc, players had to also kill 12 [Blackrock Outrunners](https://db.thealphaproject.eu/index.php?action=show_creature&id=485&filter=blackrock+outrunner&sort_order=name&pos=1&max=1).

- [ ] Change quest objective to:

`Kill 12 Blackrock Outrunners, and bring the head of their leader Tharil'zun back to Marshal Marris in Redridge.`

- [ ] Change quest description to:

`Blackrock Outrunners and Renegades are running ambushes between here and Stonewatch Keep. The leader of the Outrunners is an orc named Tharil'zun--we want this orc and his subordinates neutralized.`

`Kill the Blackrock outrunners and bring me the head of Tharil'zun.`

- [ ] Change quest progress to:

`Orc pressure from Blackrock is still tense. But have you at least rid us of Tharil'zun and his Outrunners?`

The ending text seems to be the same. 

- [ ] Set a second objective to kill 12 [Blackrock Outrunners](https://db.thealphaproject.eu/index.php?action=show_creature&id=485&filter=blackrock+outrunner&sort_order=name&pos=1&max=1)

- [ ] Set currency reward to 16 silver.

*Sources*
[Warcraft Strategy Database](https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html) (End of 0.6/Start of 0.7)
[Goblin Workshop](https://web.archive.org/web/20040830074454/http://www.goblinworkshop.com/quests/tharilzun.html) (Wayback snapshot from 30.08.2004 - Patch 0.9)
[Screenshot](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Redridge%20Mountains/images_5184.jpg) (0.5.5) | 3fc4dcdfc3000000
[Screenshot](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/from_alpha_archive_website_02043022/wow7p17.png) | 343e0787b5b4333f
