### ISSUE TITLE
TODO:  Deadmines Rework

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1455]
**Describe what needs to be implemented or enhanced**

- [ ] VanCleef level  22 : https://db.thealphaproject.eu/index.php?action=show_creature&id=639
![WoWScrnShot_050804_152826](https://github.com/user-attachments/assets/8bcc5e54-be63-4395-a41a-7b297cdd9c73)

- [ ] Smite level 21 : https://db.thealphaproject.eu/index.php?action=show_creature&id=646
![MrSmite](https://github.com/user-attachments/assets/15cadb07-1ce9-4142-a3a6-888715785923)

- [ ] Rhahk'zor level 20 : https://db.thealphaproject.eu/index.php?action=show_creature&id=644
![WOW_screenshots_350](https://github.com/user-attachments/assets/77cd994d-4b09-4e8f-9273-5ffe8906d40e)

- [ ] Defias Miner to Elite : https://db.thealphaproject.eu/index.php?action=show_creature&id=598
![9-8_3_otpopoms_l_1](https://github.com/user-attachments/assets/49bcf8ca-7748-46de-9432-a65b4a5b304a)

- [ ] Defias Worker to Elite : https://db.thealphaproject.eu/index.php?action=show_creature&id=1727
![Deadmines](https://github.com/user-attachments/assets/fb9cde8f-c1de-419a-989c-71f43346189a)

- [ ] Defias Strip Miner to Elite : https://db.thealphaproject.eu/index.php?action=show_creature&id=4416
![images_deadmines_18](https://github.com/user-attachments/assets/0a83b52c-b7be-496e-b3ec-9a70d51cfccd)

- [ ] Captain Greenskin to 20-21 level range : https://db.thealphaproject.eu/index.php?action=show_creature&id=647
![deadmines19](https://github.com/user-attachments/assets/7c606f9d-b73f-46e7-98de-61bdac9b7380)
