### ISSUE TITLE
TODO: "The Unsent Letter" Questline Total Rework

### ISSUE THREAD

**Issue by VictoriumWoW** [The-Alpha-Project/alpha-core#1458]
**The Curious Visitor (Quest ID 392)**

Source: https://web.archive.org/web/20040711223335/http://wow.allakhazam.com/db/quest.html?wquest=392

- [ ] Change the objective description from "Bring the Sealed Description of Thredd's Visitor to Baros Alexston in Stormwind." to "Perhaps Baros Alexston knows something about Bazil Thredd's strange visitor..."
- [ ] Change the quest description to the following:

"During the first years of Thredd's imprisonment, he never had any visitors. I figured that he was no longer of use to the Defias Brotherhood, so they abandoned him to die.
 
Anyways, a few months ago, that all changed. He started to get regular visits... once or twice a week. It was a strange man, quiet type. I had my suspicions, but all his papers and clearances were clean and legitimate.

His name was Maelik, here's his description. It won't do me much good now that Thredd's no longer a problem."

- [ ] Remove the requirement for the nonexistent Sealed Description of Thredd's Visitor (ID 8687)

**Shadow of the Past (Quest ID 393)**

Source: https://web.archive.org/web/20040711224307/http://wow.allakhazam.com/db/quest.html?wquest=393

- [ ] Change the objective description from "Bring the Sealed Description of Thredd's Visitor to Master Mathias Shaw in Stormwind." to "Speak with Master Mathias Shaw in Old Town."
- [ ] Remove the requirement for the nonexistent Sealed Description of Thredd's Visitor (ID 8687)

**Look to an Old Friend (Quest ID 350)**

Source: https://web.archive.org/web/20040711223318/http://wow.allakhazam.com/db/quest.html?wquest=394

- [ ] Change the next quest in the chain to Head of the Beast (ID 394) as the current next quest doesn't exist due to high ID, nor does it line up with period sources.

**Head of the Beast (Quest ID 394)**

Source: https://web.archive.org/web/20040711223318/http://wow.allakhazam.com/db/quest.html?wquest=394

- [ ] Change the objective description from "Speak to Mathias Shaw in Stormwind." to "Kill Lord Gregor Lescovar and bring his head to Master Matthias Shaw in Old Town."
- [ ] Change the quest description to the following:

"I have had my suspicions about the activities of Lord Lescovar, but have never seen or heard any proof to that effect. That Marzon would be contacting a member of the Defias Brotherhood...

Having killed VanCleef and Thredd, it would be hard to see Lescovar to justice, as your proof is certainly less without their testimony. That is not even considering the fact that Lescovar is a noble, and well connected! They are above the law, my friend.

Any justice would have to be swift, final, and silent."

- [ ] Change the previous quest in the chain to Look to an Old Friend (ID 350)
- [ ] Change the quest requirement to Lescovar's Head (ID 3516), and make it a guaranteed drop from Lord Gregor Lescovar (ID 1754) during the quest.
- [ ] Implement the scene where he enters the garden and speaks with Marzon, but make it an hourly event (I was unable to find period sources for The Attack! (ID 434)) and remove all references to the nonexistent Priestess Tyriona.
