### ISSUE TITLE
TODO: Truesilver, Thorium, Arcanite and Ooze Covered ores

### ISSUE THREAD

**Issue by VictoriumWoW** [The-Alpha-Project/alpha-core#1469]
**Truesilver**
This is an interesting case, as while the [Truesilver Bar](https://db.thealphaproject.eu/index.php?action=show_item&id=6037&filter=truesilver+bar&sort_order=name&pos=1&max=1) exists, [Truesilver Ore](https://db.thealphaproject.eu/index.php?action=show_item&id=7911&filter=truesilver+bar&sort_order=name&pos=1&max=1) does not exist in 0.5.3 and has a much higher ID. There was very little information I could find in regards to if there was a Truesilver Ore that was replaced later on, but I did find that Truesilver Bar was a requirement in the questline Sweet Amber, which consists of the oldest quests in the game (50s range for entry IDs). Also, all of the quest items in the chain not only have very low entry IDs themselves, but they're also connected together side-by-side (737 to 744). The only item in this range that isn't apart of the chain is [Deprecated Copper Ingot](https://db.thealphaproject.eu/index.php?action=show_item&id=741&sort_order=entry&pos=142&max=5195), which seems to have been the original quest item for [Sweet Amber](https://db.thealphaproject.eu/index.php?action=show_quest&id=50) before the Truesilver Bar was created. I think we should change Truesilver Bar to Truesilver Ore, make it drop from Truesilver Deposits like regular ore, and change its nonexistant displayID to 4721, which is the displayID of Truesilver Ore in beta (linked.) As for that Copper Ore, it should be restored and take the place of Truesilver Bar in the questline (needs research.)

**Thorium**
The only Thorium gameobject that could exist in 0.5.3 is [Small Thorium Vein](https://db.thealphaproject.eu/index.php?action=show_go&id=324&filter=small+thorium&sort_order=name&pos=1&max=3), which has an extremely low entry ID of 324, which seems to be the lowest entry ID for any vein or lode. However, it has an extremely high displayID that does not exist in 0.5.3. Looking into this, I discovered this screenshot from the beta:
![thorium](https://github.com/user-attachments/assets/5cd94a42-af3e-44be-8985-a280107c446c)
This shows us two things: Assuming that this is the same gameobject as Small Thorium Vein, then not only did it have a different displayID back then, but it also had the name "Thorium Lode", which implies that at this time there may not have been the other "tiers" of Thorium ore veins like Rich Thorium Veins. It's difficult to see, but the displayID appears to match up to ID 48. As for Thorium Ore itself, it has an entry ID too high, but I found something of interest in ItemDisplayInfo:

![thoriumicon](https://github.com/user-attachments/assets/ad829fb8-558f-4f76-b8b6-8d9fa60c8fb6)

In ItemDisplayInfo in 0.5.3 exists displayIDs with icons that have peculiar and relevant names, those being Thorium and Arcanite (we'll get to Arcanite later.) What's worth noting is the displayID for Thorium ore is much higher than the other ores, implying that it was added at a later date than even Arcanite. However, [Thorium Ore](https://db.thealphaproject.eu/index.php?action=show_item&id=10620&filter=copper+ore&sort_order=name&pos=1&max=1) in Beta, which does not exist in 0.5.3, has a much lower displayID, the icon having an internal name of Mithril. Also, there is an ID gap between a gray item and Copper Ore (2767 to 2769). I think we should add Thorium Ore at ID 2769 with a displayID of 5699 and item level of 40, and make it drop from Small Thorium Veins while said veins are renamed to Thorium Lode with the displayID 48.

**Arcanite**
Right behind the entry ID of Thorium Lode is [Arcanite Lode](https://www.wowhead.com/classic/object=323/arcanite-lode). It currently doesn't exist in the database, but considering its very low entry ID and the fact that its displayID exists in 0.5.3 it probably existed like Thorium Lode. As for Arcanite Ore, there isn't one even in Beta. However, the icon and displayID for an Arcanite Ore does exist in ItemDisplayInfo. It should be added at entry ID 2768 as a common quality item with an item level of 45 (given the item level pattern of ores like Thorium with their ores and bars) and displayID of 4679. There aren't many places where Arcanite Lodes could've spawned, but they may have appeared at certain spots in the more well-developed areas like Blasted Lands, Eastern Plaguelands, and Silithus, possibly in the places that Thorium Lodes would spawn in those zones. We know NPCs like Flight Masters existed in areas like Eastern Plaugelands during this time, so it's not a stretch to believe they may have been located in caves or similar locations.

**Ooze Covered Veins**
It seems like Ooze Covered Veins didn't exist at all in 0.5.3, as not only do their displayIDs not exist in 0.5.3, but also their IDs are quite high (120K range), higher than many Beta Scarlet Monastery and Gnomeregan objects interestingly enough. They should not be spawned in.

**TODO List**
- [ ] Replace Truesilver Bar with the data of Truesilver Ore, mainly the name and displayID
- [ ] Make Truesilver Ore drop from Truesilver Deposits
- [ ] Rename Small Thorium Vein to Thorium Lode, and spawn it in the same locations as it does in Beta/Release _except_ in places that weren't finished/populated in 0.5.3 (Eastern Plaguelands, Winterspring, etc.)
- [ ] Copy the data of Thorium Ore to entry ID 2769 with a displayID of 5699, and make it drop from Thorium Lodes
- [ ] Add Arcanite Ore at entry ID 2768 with an item level of 45 and displayID of 4679
- [ ] Add Arcanite Lode at entry ID 323 with a Mining requirement of 310 and a displayID of 48, and spawn it in the locations of Thorium Lodes in max-level areas that are well-developed.
- [ ] Remove the deprecated status of Deprecated Copper Ingot, and add it as the quest requirement for Sweet Amber (ID 50)

**Comment by jdmccathie** [comment]
In many works of fantasy, truesilver (or alchemical silver) is not a naturally occuring substance. It is most often created via alchemy. This may have been the original intended method for introducing truesilver to warcraft, given shortly after the introduction of truesilver ore that mithril-to-truesilver transmutation was also implemented.

**Comment by VictoriumWoW** [comment]
While this is true, the model for Truesilver nodes exist in 0.5.3:
![truesilver](https://github.com/user-attachments/assets/d3c4c0f4-19fe-48e7-8e45-6f390eb64412)
Not only that, but and the entry ID of Truesilver Deposit is low enough to where it undoubtably existed in 0.5.3: https://db.thealphaproject.eu/index.php?action=show_go&id=2047&filter=truesilver&sort_order=name&pos=2&max=4

Blizzard is known to take artistic liberties with generic or semi-generic fantasy races, materials, etc. A good example of this would be the Dragonflights, and how none but the Black Dragonflight (who were corrupted by the Old Gods) are evil. It's why the Dragon Isles raid was scrapped early into development, to where only the outline of its terrain exists in 0.5.3. It's not a stretch to believe that Truesilver falls into this category, especially given that its node model and Deposit gameobject exists in 0.5.3.
