### ISSUE TITLE
TODO: Complete pet/charm/mind control behavior.

### ISSUE THREAD

**Issue by Fluglow** [The-Alpha-Project/alpha-core#281]
**Describe what needs to be implemented or enhanced**
The ability to have temporary pets should be available for all units. Players should also be able to have permanent pets that have persistent names (and other states?).
Pets are actively being worked on, and I'll keep a list of missing core behavior below. The list will be updated when new requirements arise or features are implemented.

* [x] Basic beast taming spell handling.
* [x] Pet spell action bar loading.
* [ ] Basic pet command state application (handling packets and storing values to pass to AI).
* [ ] Pet spell cast packet handling.
* [ ] Pet SpellManager usage.
* [ ] Permanent pet summoning (hunter pet / warlock pets).
* [ ] Database persistency.
* [ ] Pet talents and training for hunter pets.
	* Seems very similar to vanilla, but requires research.
* [ ] Temporary, on-spawn summoned pets for creatures.
* [ ] Temporary, time-limited possess pet behavior (charm beast). 
* [ ] Player mind control behavior (?).
* [ ] At least basic AI so pets are useful in regular gameplay.
    * Movement with player when following, stay behavior and combat movement.
    * Pathing or despawning when a path doesn't exist.

**Expected end result**
* Pets are summonable, persistent and fully commandable for hunters and warlocks.
* Units can temporarily mind control/charm other units and control/command them.
* Players have the ability to teach their permanent pets spells and talents. Hunters can learn pet spells by taming and playing with different pets, warlocks via demon trainers.
* Creatures in the world have pets where intended with working combat AI.

**Guidance**
Most work being done on pets should be isolated into pet-related files such as PetManager.
If you want to contribute to implementing this system (including sharing related screenshots etc. that might help), please contact me via the project's Discord. I'm actively working on pet behavior in [Fluglow/alpha-core/tree/pets](/Fluglow/alpha-core/tree/pets).

**Comment by T1ti** [comment]
Imps can currently auto attack, not sure of the intended behavior in  but as far as I know they could never attack in vanilla.

**Comment by Alonin** [comment]
When a warlock logs out, their summoned pet remains in the world as a hostile creature. Unsure if the same happens with hunter pets.
