### ISSUE TITLE
TODO: Rework Mathystra Relics quest

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#652]
**Describe what needs to be implemented or enhanced**
Server is using the already changed version of [Mathystra Relics](https://classic.wowhead.com/quest=951/mathystra-relics). Blizz changed it when they moved Blackfathom Deeps from Ruins of Mathystra to Zoram Strand in Ashenvale. Several changes need to be made in order to return it to its original form. I've written this report in a way so that different points can be done by multiple people if necessary:

- [ ] **Change the name of Mathystra Relics (Quest ID 951) quest to Blackfathom Relics**

Reasoning
This is the original name of this quest. 

**Source**
First Screenshot

- [ ] **Change the name of [OldBlackfathom MAGIC Relic] (Item ID 5331) to [Blackfathom Relic]**

Reasoning
The original quest required three types of quest items. 2x Mathystra Relic (Item ID 5273), 2x Elven Cup Relic (Item ID 5330) and 2x Blackfathom Relic (Item ID 5331). Only this version of the item survived, so it'll have to be changed into the quest item.

- [ ] **Change [Blackfathom Relic]'s (Item ID 5331) item properties.**

Change item's bonding to 4 - quest
Change maximum stack to 2
Remove the option to sell those items to vendors

Reasoning
Because it's either the old version of Blackfathom Relic, or it was changed over time, those changes need to hapen in order to make it a quest item again. Got data from 

**Source**
First and second screenshot

- [ ] **Change the quest objectives to require 2x Mathystra Relic (Item ID 5273), 2x Elven Cup Relic (Item ID 5330) and 2x Blackfathom Relic (Item ID 5331)**

Reasoning
Those were the original items required for this quest

**Source**
First Screenshot

- [ ] **Add Elven Cup Relic (Item ID 5330) and 2x Blackfathom Relic (Item ID 5331) to game objects' loot tables.**

There are 3 different game objects called Mathystra Relic, that should contain their respective relic quest items. Their IDs are:
13872 (looks like a chalice) should contain an Elven Cup Relic (Item ID 5330) 
12654 (looks like a Night Elf) should contain a Mathystra Relic (Item ID 5273)
13360 (looks like a ball) should contain a Blackfathom Relic (Item ID 5331)

**Source**
Second and third screenshot

- [ ] **Change the text when completing the quest**

Unfortunately the initial quest text is still unaccounted for, possibly lost forever, but the archive contains the text for turning in the quest. I'll spare rewriting it from the fourth screenshot here not to waste anymore space in this lenghty post.

**Source**
Fourth screenshot

**Screenshots**
All from patch 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4459.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4335.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4358.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4460.jpg

**Comment by dirtbikercj** [comment]
I have the reworked version almost completed, just need to test some more. However with the reworked version not having the updated quest text it makes absolutely no sense when doing it from a player perspective. So should I open a pull request for it and we mark this partially completed, or do we hold off until we can get further clarification on that information?

**Comment by GizzleBizzle** [comment]
I've separated the tasks, so You can update what is finished (I created this report before I got the hang of GitHub).

**Comment by GrenderG** [comment]
Some comments:

```
12654 (looks like a Night Elf) should contain a Mathystra Relic (Item ID 5273)
13360 (looks like a ball) should contain a Blackfathom Relic (Item ID 5331)
```
You swapped them I think, according to the screenshots the Night Elf statue should contain [PH] Blackfathom Relic and the ball should contain [PH] Mathystra Relic.

---
We should add the `[PH]` text to the item names, it was probably in 0.5.3 too (it means PlaceHolder).

---
With the initial quest do you mean Objectives text @GizzleBizzle? We can safely assume that instead of `Bring 6 Blackfathom Relics to Onu at the Grove of the Ancients.` it was something like `Bring 2 Blackfathom Relics, 2 Mathystra Relics and 2 Elven Cup Relics to Onu at the Grove of the Ancients.`

---
We should probably rename the GameObjects too to the corresponding item they drop.

---
We also need to update the display_ids of these 3 items, they use wrong ones at this moment.

**Comment by GizzleBizzle** [comment]
**First Comment**
I agree, I even know why I confused them. Back when I researched this issue I saw [Blackfathom Relic](https://db.thealphaproject.eu/index.php?action=show_item&id=5331&filter=blackfathom&sort_order=name&pos=1&max=1)'s icon, which looks like an orb of some sorts so I was hypothesising if they should drop from the ball game objects.

Haven't found any data confirming my claim, and I must have forgotten to change the info back in my docs.

**Second Comment**
Yes, as it is blizzlike for that time-period.

**Third and Fourth Comment**
What I meant by changing the quest text is that every quest has a different text when:
- Initial quest  (when taking the quest from the NPC or looking at it in the quest log)
- Progress  (when talking to the NPC when the quest isn't finished, yet, but is already present in our quest log)
- Completion (the "choose your reward" part
 
I have found only the second and third part so I wanted to make others aware that the first part could still be potentially different from the vanilla verion of the quest (if there even are different versions of the initial quest text). Even though the vanilla version of the initial quest text can be implemented as it fits the 0.5.5 parts very well and won't confuse players in any way, it still has a "subject to potential change" tag in my mind, since I haven't proven if it should look like that in 0.5.3, yet.

I just want to have a solid proof for anything I report. It's a part of my methodology. I wouldn't want to sidetrack the project with "how I hope/wish it should have worked". The same goes for the objects in the fourth comment. I haven't found any info about those objects having other names, yet, so I didn't suggest changing them as it may turn out not to be blizzlike in the end.
