### ISSUE TITLE
TODO: Rework Stockades

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#689]
Several things are off when compared to the 0.5.5 screenshots found in the catalogue.

- [x] Add [Targorr the Dread](https://db.thealphaproject.eu/index.php?action=show_creature&id=1696&filter=targorr&sort_order=name&pos=1&max=1)'s  (ID 1696) potential spawn points to the following coordinates:
![Bez tytułu](https://user-images.githubusercontent.com/111394734/196787070-6633889f-1d50-45e3-aa9a-1cc9ab122582.png)
![targor 2](https://user-images.githubusercontent.com/111394734/196800627-6364ad38-b5f4-4f83-a180-753227d69cde.png)

Source
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Stockades/images_6043.jpg

- [x] Change parameters of the following mobs:

[Targorr the Dread](https://db.thealphaproject.eu/index.php?action=show_creature&id=1696&filter=targorr&sort_order=name&pos=1&max=1) (ID 1696)
- health_min - 2052
- health_max - 2052

[Defias Captive](https://db.thealphaproject.eu/index.php?action=show_creature&id=1707&filter=defias&sort_order=name&pos=5&max=46) (ID 1707)
- health_min - 1890
- health_max - 2052

[Defias Convict](https://db.thealphaproject.eu/index.php?action=show_creature&id=1711&filter=defias&sort_order=name&pos=8&max=46) (ID 1711)
- health_min - 2052
- health_max - 2166

[Defias Inmate](https://db.thealphaproject.eu/index.php?action=show_creature&id=1708&filter=defias&sort_order=name&pos=16&max=46) (ID 1708)
- health_min - 2052*
- health_max - 2166

[Hammock](https://db.thealphaproject.eu/index.php?action=show_creature&id=1717&filter=hamhock&sort_order=name&pos=1&max=1) (ID 1717)
- health_min - 2667
- health_max - 2667

[Dextren Ward](https://db.thealphaproject.eu/index.php?action=show_creature&id=1663&filter=dextren&sort_order=name&pos=1&max=1) (ID 1663)
- health_min - 2331
- health_max - 2331

[Defias Insurgent](https://db.thealphaproject.eu/index.php?action=show_creature&id=1715&filter=defias&sort_order=name&pos=17&max=46) (ID 1715)
- health_min - 2166*
- health_max - 2331*

* Level 24 Defias Inmates as well as lvl 25/26 Insurgents are not present on screenshots from the catalogue, but there are multiple screenshots of different Defias mobs from Stockades having the same amount of health at this level, so there is a strong possibility those mobs follow the same rule.

Sample Sources
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Stockades/images_6068.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Stockades/images_6073.jpg

- [x] Relocate [Dextren Ward](https://db.thealphaproject.eu/index.php?action=show_creature&id=1663&filter=dextren&sort_order=name&pos=1&max=1) (ID 1663)

*Reasoning*
Dextren, along with some Defias mobs are currently floating in Limbo as that part of Stockades isn't built, yet.
It isn't known right now where he should reside, yet he drops a quest item so I found him a temporary place where he can reside until his real location is found.

![Dextren](https://user-images.githubusercontent.com/111394734/196806823-6490229c-6c64-4133-89dc-4d3cd7dbb185.png)

- [x] Change weapon models
[Defias Convict](https://db.thealphaproject.eu/index.php?action=show_creature&id=1711&filter=defias&sort_order=name&pos=8&max=46) (ID 1711) should wield [[Monster - Sword, Short Basic]](https://db.thealphaproject.eu/index.php?action=show_item&id=1896&filter=monster+-+sword&sort_order=name&pos=8&max=16) (ID 1896) and [[Monster - Shield, Buckler Wooden]](https://db.thealphaproject.eu/index.php?action=show_item&id=1961&filter=Monster+-+shield&sort_order=name&pos=2&max=10) (ID 1961)
[Defias Insurgent](https://db.thealphaproject.eu/index.php?action=show_creature&id=1715&filter=defias&sort_order=name&pos=17&max=46) (ID 1715) should wield [[Monster - Staff, Crooked]](https://db.thealphaproject.eu/index.php?action=show_item&id=1908&filter=Monster+-+Staff&sort_order=name&pos=4&max=10) (ID 1908)

Sources
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Stockades/images_6061.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Stockades/images_6068.jpg

- [x] Implement a chain-pull between [Hammock](https://db.thealphaproject.eu/index.php?action=show_creature&id=1717&filter=hamhock&sort_order=name&pos=1&max=1) (ID 1717) and [Defias Insurgents](https://db.thealphaproject.eu/index.php?action=show_creature&id=1715&filter=defias&sort_order=name&pos=17&max=46) (ID 1715) in his room

According to the source Hamhock should aggro together with his Defias Insurgent bodyguards and vice-versa.

Source
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Stockades/images_6061.jpg

**Comment by GrenderG** [comment]
Task 5 still needs to be implemented as we are lacking proper chaining pull logic at this moment.

**Comment by mindphluxnet** [comment]
This can be closed as creature groups are now working. Just tested it, aggroing Hamhock also adds the other two.
