### ISSUE TITLE
TODO: Mulgore NPC adjustment.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#695]
- [x] Relocate [Seer Graytongue](https://db.thealphaproject.eu/index.php?action=show_creature&id=2982&filter=seer&sort_order=name&pos=12&max=18) (ID 2982) to the following coordinates:
![Seer's location](https://user-images.githubusercontent.com/111394734/197359958-0c45a02c-6ade-4a8d-9605-15ad7b478694.png)

Source (third day of patch 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/worldofwarcrafttauren__041604_004-806688.jpg

- [x] Change [Arra'chea](https://db.thealphaproject.eu/index.php?action=show_creature&id=3058&filter=arra&sort_order=name&pos=1&max=3)'s (ID 3058) Display ID to either 1230, 1231, 1241, 1308, 1451, 1452, 2768 (they're identical)

Source (second week of patch 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_211150.jpg

- [x] Relocate [Skorn Whitecloud](https://db.thealphaproject.eu/index.php?action=show_creature&id=3052&filter=skorn&sort_order=name&pos=1&max=1) (ID 3052) to the following coordinates:
![Skorn](https://user-images.githubusercontent.com/111394734/197360264-7ba62af4-5ce2-4d53-b665-5f0285c10bb7.png)

Source from 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/normal_WoWScrnShot_032304_043408.jpg
Source from 0.6
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_050404_072154.jpg

- [ ] Implement [Skorn Whitecloud](https://db.thealphaproject.eu/index.php?action=show_creature&id=3052&filter=skorn&sort_order=name&pos=1&max=1)'s (ID 3052) new gossip text with players, who finished [The Demon Scarred Cloak
](https://db.thealphaproject.eu/index.php?action=show_quest&id=770&filter=demon+scarred&sort_order=Title&pos=1&max=1) quest (ID 770).

Source (second week of patch 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_050404_072154.jpg

- [x] Equip [Brave Strongbash](https://db.thealphaproject.eu/index.php?action=show_creature&id=3215&filter=strongbash&sort_order=name&pos=1&max=1) with [[Monster - Shield, Buckler Wooden]](https://db.thealphaproject.eu/index.php?action=show_item&id=1961&filter=Monster+-+shield&sort_order=name&pos=2&max=10) to use with his current spear.

Source from 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/normal_WoWScrnShot_032304_043316.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/normal_WoWScrnShot_032304_043347.jpg

- [ ] Remove [Kar Stormsinger](https://db.thealphaproject.eu/index.php?action=show_creature&id=3690&filter=kar+stormsinger&sort_order=name&pos=1&max=1) (ID 3690) and [Harb Clawhoof](https://db.thealphaproject.eu/index.php?action=show_creature&id=3685&filter=Harb&sort_order=name&pos=1&max=1) (ID 3685)

Source from 0.6
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/wow04041602_1082104539.jpg

- [x] Set [Melor Stonehoof](https://db.thealphaproject.eu/index.php?action=show_creature&id=3441&filter=melor&sort_order=name&pos=1&max=1)'s (ID 3441) level to 68 and perhaps change his DisplayID

There is a slight problem here. The only source in the catalogue shows only Melor's portrait and I'm almost entirely sure that model was created in a later patch. There are 3 unused DisplayIDs for Taurens wearing trousers - 2578, 2895 and 3773.  2578 was used as a placeholder by blizzard for some deprecated NPCs that aren't present in the game anymore. 3773 Resembles the source the most (even though there still are some differences). My suggestion is to use either DisplayID to get rid of the cube until more screenshots resurface and we actually have something to work with.

Source from 0.6
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_163736.jpg

- [x] Change [Taloned Swoop's](https://db.thealphaproject.eu/index.php?action=show_creature&id=2971&filter=taloned&sort_order=name&pos=1&max=1) (ID 2971) DisplayID to either 388, 1105, 1106, 1228, 1229, 1419 (they're identical)

Source from 0.6
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_211150.jpg

- [x] Change [Bristleback Shamans](https://db.thealphaproject.eu/index.php?action=show_creature&id=2953&filter=bristleback&sort_order=name&pos=8&max=10)' (ID 2953) DisplayID to either 1254, 1274, 1341, 1342, 1343, 1344, 1345, 1346, 1420, 1967, 3825 (they're Identical)

Source (from early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/worldofwarcrafttauren__041604_009-806693.jpg

- [x] Relocate [Mull Thunderhorn](https://db.thealphaproject.eu/index.php?action=show_creature&id=2948&filter=Thunderhorn&sort_order=name&pos=5&max=6) (ID 2948) to these coordinates
![Mull Thunderhorn](https://user-images.githubusercontent.com/111394734/197363960-8fd783ea-f195-4eb4-b31c-5c6a6b4afec3.png)

Source (anywhere between 0.5 and 0.7)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWSS79.jpg

- [x] [Flatland Cougars](https://db.thealphaproject.eu/index.php?action=show_creature&id=3035&filter=flatland&sort_order=name&pos=1&max=2) should use [Agonizing Pain](https://db.thealphaproject.eu/index.php?action=show_spell&id=3247&filter=agonizing&sort_order=Name_enUS&pos=1&max=2)

Source (from early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_052858.jpg

- [x] [Prarie Wolves](https://db.thealphaproject.eu/index.php?action=show_creature&id=2958&filter=prairie&sort_order=name&pos=3&max=4) and [Prarie Wolves Alpha](https://db.thealphaproject.eu/index.php?action=show_creature&id=2960&filter=prairie&sort_order=name&pos=4&max=4) should use [Threatening Growl](https://db.thealphaproject.eu/index.php?action=show_spell&id=5781&filter=growl&sort_order=Name_enUS&pos=11&max=11)

Source
From early 0.6
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/skills.jpg
From 0.8
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/20040731%20033448%20mmmprairiewolf.jpg

- [x] [Swoops](https://db.thealphaproject.eu/index.php?action=show_creature&id=2970&filter=swoop&sort_order=name&pos=2&max=4) should use the [Swoop](https://db.thealphaproject.eu/index.php?action=show_spell&id=5708&filter=swoop&sort_order=Name_enUS&pos=1&max=1) ability

Source (from early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/561866-534914_20040426_080.jpg

- [x] [Palemane Tanners](https://db.thealphaproject.eu/index.php?action=show_creature&id=2949&filter=tanner&sort_order=name&pos=2&max=3)  should use [Nature's Wrath](https://db.thealphaproject.eu/index.php?action=show_spell&id=5176&filter=wrath&sort_order=Name_enUS&pos=2&max=35)

Source (from early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_150803.jpg

- [x] Change [Mahnott Roughwound](https://db.thealphaproject.eu/index.php?action=show_creature&id=3077&filter=mahnott&sort_order=name&pos=1&max=1)'s weapon to [[Item Monster - Sword2H, Black Metal Hilt]](https://db.thealphaproject.eu/index.php?action=show_item&id=6224)

Source (from early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/worldofwarcrafttauren__041604_023-806707.jpg

- [x] Slightly move [Baine Bloodhoof](https://db.thealphaproject.eu/index.php?action=show_creature&id=2993&filter=baine&sort_order=name&pos=1&max=1)

His coordinates:
Map: 1
Zone: 222
ADT: [36,32]
X: -2338.450
Y: -399.795
Z: -9.816
MapZ: -9.757
O: 3.752

Source (from 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/images_6706.jpg

- [x] Spawn [Supervisor Fizsprocket](https://db.thealphaproject.eu/index.php?action=show_creature&id=3051)

He isn't spawned anywhere, since in 1.12.1 the model of this mine is different. Source material says, that he should be at the end of the mine, so I found him a nice spot until the screenshot with his exact spot resurfaces.

Map: 1
Zone: 215
ADT: [35,34]
X: -1766.033 
Y: -1193.097
Z: 84.164
MapZ: 84.164
O: 6.259

Source
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/rushjournal_queue.jpg

**Comment by geo-tp** [comment]
For identical models, we should look at the scale of each display_id to be able to determine which one fits the most.


Example for Bristleback mobs :
![Capture d’écran_2022-10-23_00-26-37](https://user-images.githubusercontent.com/72315006/197364543-4bb28359-f4f9-402f-8540-f01c787d7e4b.png)

SQL query : 
```
select ID, CreatureModelScale from alpha_dbc.CreatureDisplayInfo where ID in (1274, 1341, 1342, 1343, 1344, 1345, 1346, 1420, 1967, 3825);
```

**Comment by GizzleBizzle** [comment]
- [ ] Arm Bluffwatchers with [Monster - Axe, 2H Single Bladed](https://db.thealphaproject.eu/index.php?action=show_item&id=5289&filter=monster+-+axe&sort_order=name&pos=3&max=8)

**Source**
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Thunder%20Bluff/WoWScrnShot_043004_211456.jpg
