### ISSUE TITLE
TODO: Rework Talents (stage 1) 

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#702]
- [ ] Rework the talent listing process
Only the first rank of a talent, that is either available or unavailable for learning, should be shown in the talents tab. Players should see the second rank's details only if they had learnt the previous one.

The incorrect way:
- Frost Power (rank 1)
- Frost Power (rank 2)
- Frost Power (rank 3)
... all the way to about 16

The correct way:
- Frost Power (rank 1)
If you want info about the next rank, learn the first one.

Source from 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Dun%20Morogh/WoWScrnShot_031804_233102.jpg

- [ ] Implement a check to show talents relevant to the class which is played
Classes should only see the talents that augment the spells, which they use. It should be impossible to take talents related to shadow magic while playing a warrior/paladin/rogue/mage or anyone else, who doesn't use a single shadow spell.

I'll detail what given classes should have on their "Magic Talents" list

Rogues/Hunters/Warriors
- Only resistances

Mana users, who can't use wands
- Resistances
- Talents of schools they use (paladins = holy talents / Druids/Shamans = nature talents)
- Meditation talent

Mana users, who can use their wands
- Resistances
- Talents of schools they use (warlocks = fire and shadow talents/ priests = holy and shadow talents)*
- Meditation talent
- Wand talents***

Source from 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/screenhot_betatest_quest4.jpg

- [ ] Implement requirements for all Weapon Specialization talents.
 All talents with the word "specialization" in them should require having the corresponding weapon's skill learnt in order to be learnt by the class.

Now classes can pick axe specialization before they even learn to use axes. All [weapon] specialization talents should require (1) skill of that weapon type to make those talents available for learning. **

Source from 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Dun%20Morogh/WoWScrnShot_031804_233102.jpg

* Yes, I'm aware that Arcane talents do not exist. That's a separate issue.
** At least for the time being, I haven't found the right screenshots, yet, but I'm almost sure the next ranks of Weap. Spec. should require more than just 1 point of weapon skill to be learnt.

The first stage is mostly cosmetic to make the tab less cluttered. Concurrent stages will follow when I accumulate enough data to be sure the changes will be blizzlike.

**Comment by GrenderG** [comment]
This issue should be completely fixed @GizzleBizzle. The PTR has been updated, if you can please confirm that everything is working as described here. :+1:
