### ISSUE TITLE
TODO: Mulgore Quests adjustment

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#718]
- [x] [The hunt begins](https://db.thealphaproject.eu/index.php?action=show_quest&id=747&filter=the+hunt+begins&sort_order=Title&pos=1&max=1) quest should ask for 4 [plainstrider meat](https://db.thealphaproject.eu/index.php?action=show_item&id=4739) and 4 [plainstrider feathers](https://db.thealphaproject.eu/index.php?action=show_item&id=4740).

Source (from 0.5.4)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/screenhot_gamespotkor_024.jpg

- [x] [Sharing the land](https://db.thealphaproject.eu/index.php?action=show_quest&id=745&filter=sharing&sort_order=Title&pos=1&max=1) quest should award 1 silver and 35 copper.

Source (from 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/images_6706.jpg

- [x] [A humble task](https://db.thealphaproject.eu/index.php?action=show_quest&id=752&filter=a+humble+task&sort_order=Title&pos=1&max=3) quest shouldn't award any gold.

Source (from early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/worldofwarcrafttauren__041604_001.jpg

- [ ] Water well cleansing chain should be available only for Taurens
Quests in this chain include:
- [Poison Water](https://db.thealphaproject.eu/index.php?action=show_quest&id=748&filter=poison+water&sort_order=Title&pos=1&max=1)
- [Winterhoof Cleansing](https://db.thealphaproject.eu/index.php?action=show_quest&id=754) 
- [Thunderhorn Totem](https://db.thealphaproject.eu/index.php?action=show_quest&id=756)
- [Thunderhorn Cleansing](https://db.thealphaproject.eu/index.php?action=show_quest&id=758)
- [Wildmane Totem](https://db.thealphaproject.eu/index.php?action=show_quest&id=759)
- [Wildmane Cleansing](https://db.thealphaproject.eu/index.php?action=show_quest&id=760)

Reasoning
The item used to cleanse the wells is tauren-specific and it worked the same way in vanilla.

- [x] Implement an event for [Rite of Vision](https://db.thealphaproject.eu/index.php?action=show_quest&id=772)

After consuming [Water of the Seers](https://db.thealphaproject.eu/index.php?action=show_item&id=4823&filter=water&sort_order=name&pos=45&max=51) the [Plains Vision](https://db.thealphaproject.eu/index.php?action=show_creature&id=2983&filter=plains+vision&sort_order=name&pos=1&max=1) will appear and it should move to the cave, where [Seer Wiserunner](https://db.thealphaproject.eu/index.php?action=show_creature&id=2984) resides.

Source (from early 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_161008.jpg
