### ISSUE TITLE
TODO: Update Hunter Pet Trainers

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#789]
Pet Trainers
=========

Source
------

https://web.archive.org/web/20040819193111/http://wow.allakhazam.com/db/moblist.html?mobtype=7
https://web.archive.org/web/20040607115529/http://db.wowvault.ign.com/locations/index.php?type=6

Jadenvis Seawatcher
--------
- [ ] Update Subname

3700 Jadenvis Seawatcher Crawler Trainer
http://web.archive.org/web/20041115022719/http://wow.allakhazam.com/db/mob.html?wmob=3700
https://db.thealphaproject.eu/index.php?action=show_creature&id=3700&filter=jadenvis&sort_order=name&pos=1&max=1
Located Darkshore

Claude Erksine 
------

- [ ] Update Subname
- [ ] Update Display id

3545 Claude Erksine Bear Trainer
http://web.archive.org/web/20041114205632/http://wow.allakhazam.com/db/mob.html?wmob=3545
https://db.thealphaproject.eu/index.php?action=show_creature&id=3545&filter=pet+trainer&sort_order=name&pos=1&max=23
Located in Loch Modan
This dwarf probably use display_id 428 as Grunenstur Balindom <Crocilisk Trainer> in Loch Modan (we have evidences for him) 

Grokor
------
- [ ] Update Subname
- [ ] Move to good position
- [ ] Update Display id

3622 Grokor Boar Trainer
http://web.archive.org/web/20041114224109/http://wow.allakhazam.com/db/mob.html?wmob=3622
https://db.thealphaproject.eu/index.php?action=show_creature&id=3622&filter=pet+trainer&sort_order=name&pos=3&max=23
Located in Durotar
Display_id is probably 1139 for 0.5.3

![grokor](https://user-images.githubusercontent.com/72315006/206717641-7dfb3acf-f4c9-4e11-9da4-eca0c046d7be.jpg)

Harruk
------

- [ ] Update Subname
- [ ] Update Display id

3620 Harruk Crocilisk Trainer
http://web.archive.org/web/20041114223307/http://wow.allakhazam.com/db/mob.html?wmob=3620
https://db.thealphaproject.eu/index.php?action=show_creature&id=3620&filter=pet+trainer&sort_order=name&pos=4&max=23
Located in Durotar
Display_id is probably 1139 for 0.5.3

Rarck
-----

- [ ] Update Subname
- [ ] Change flag
- [ ] Spawn
- [ ] Update Display id

3625 Rarck Raptor Trainer
Display_id is probably 1139 for 0.5.3
http://web.archive.org/web/20041114204215/http://wow.allakhazam.com/db/mob.html?wmob=3625
https://db.thealphaproject.eu/index.php?action=show_creature&id=3625&filter=rar&sort_order=name&pos=13&max=15
Located in Durotar
![rarck](https://user-images.githubusercontent.com/72315006/206717737-ed12e194-fed8-4f96-888f-cd129b07923d.jpg)

Kurll
-----

- [ ] Update Subname
- [ ] Change flag
- [ ] Move to good position
- [ ] Update Display id

3621 Kurll Cat Trainer
Display_id is probably 1139 for 0.5.3
https://db.thealphaproject.eu/index.php?action=show_creature&id=3621&filter=kurl&sort_order=name&pos=1&max=1

![kurll](https://user-images.githubusercontent.com/72315006/206717816-a437f50a-a954-4880-9b55-67c6107fc903.png)
![Capture d’écran_2022-12-09_05-10-07](https://user-images.githubusercontent.com/72315006/206723830-7417efea-3139-4ee9-a7a7-3a0f94e7858b.png)

Bernie Heinstein
-----

- [ ] Update Subname
- [ ] Change flag

3546 Bernie Heisten Spider Trainer
https://db.thealphaproject.eu/index.php?action=show_creature&id=3546&filter=bernie&sort_order=name&pos=1&max=1
![Capture d’écran_2022-12-09_05-13-46](https://user-images.githubusercontent.com/72315006/206723575-3d2a257a-6840-4efd-9379-5359b9aab7d1.png)

Alanndarian
----

- [ ] Update Subname
- [ ] Change flag
- [ ] Move to good position

3702 Alanndarian Nightsong Tallstrider Trainer
https://db.thealphaproject.eu/index.php?action=show_creature&id=3702&filter=alannd&sort_order=name&pos=1&max=1

![tailst](https://user-images.githubusercontent.com/72315006/206721618-5a8074e2-b1e1-4cd5-abf2-a984df2c9535.jpg)

![Capture d’écran_2022-12-09_05-17-46](https://user-images.githubusercontent.com/72315006/206723541-fefd79af-ef30-4e9c-90ed-632775a8bb63.png)

Karrina
----

- [ ] Update Subname
- [ ] Update Display id

2879 Karrina Mekenda Bird Trainer
http://web.archive.org/web/20041114173030/http://wow.allakhazam.com/db/mob.html?wmob=2879
https://db.thealphaproject.eu/index.php?action=show_creature&id=2879&filter=karrina&sort_order=name&pos=1&max=1
Actually located in SW, she should probably be moved somewhere else (but no evidences yet)
She should use display id 2585 like other females dwarf pet trainer.

Harb
----
- [ ] Update Subname
- [ ] Change flag
- [ ] Move to good pos
- [ ] Update Display id

3685 Harb Clawhoof Cat Trainer
https://db.thealphaproject.eu/index.php?action=show_creature&id=3685&filter=Harb+claw&sort_order=name&pos=1&max=1

![taurent cat](https://user-images.githubusercontent.com/72315006/206718117-c9c1f9a2-4a5e-4257-9d4e-fb27c8490793.jpg)
![Capture d’écran_2022-12-09_05-09-10](https://user-images.githubusercontent.com/72315006/206723905-d21b67ce-04e3-4555-95fe-eb2d3e707a60.png)

Jackson Bayne
-----

- [ ] Spawn
- [ ]  Update Display id

2939 Jackson Bayne Boar Trainer
Display_id is probably 428 as other humans pet trainer
![Capture d’écran_2022-12-09_21-47-06](https://user-images.githubusercontent.com/72315006/206793551-faa35023-77ee-4603-a9d4-35224bb1d24c.png)

Rebald Yorglun
----

- [ ] Spawn

4621 Rebald Yorglun Raptor Trainer
![WoWScrnShot_052304_075847](https://user-images.githubusercontent.com/72315006/206830979-97f5cfaf-1953-47dc-9e6d-578ff7c001bd.jpg)

![Capture d’écran_2022-12-09_21-53-04](https://user-images.githubusercontent.com/72315006/206794357-d2a2ac6c-e3d7-4eec-8510-18bf7417cd34.png)

Laer
----

- [ ] Spawn
- [ ] Update Subname
- [ ] Change Flag

3689 Laer Stepperrunner Wolf Trainer
Located in Mulgore

- wowpython:
1 -2481.16 -473.534 -8.74122 4.88692

![Capture d’écran_2022-12-09_05-20-04](https://user-images.githubusercontent.com/72315006/206723460-fc4a9528-e41b-40b8-b5fc-40bfca2c6e9f.png)

Zudd
----

- [ ] Update Subname
- [ ] Change Flag

3624 Zudd Scorpid Trainer
Located in STV
![Capture d’écran_2022-12-09_05-12-47](https://user-images.githubusercontent.com/72315006/206723664-cf9457bc-0fd6-4b76-9bc8-9696a49179ab.png)
![Capture d’écran_2022-12-14_21-15-36](https://user-images.githubusercontent.com/72315006/207704963-e74e55d9-187c-4abb-b6ec-ecca767d55f4.png)

Tursk
----

- [ ] Spawn
- [ ] Update Subname
- [ ] Change Flag
- [ ] Update Display Id

3623 Tursk Crawler Trainer
Located in Durotar
Display_id is probably 1139 for 0.5.3
![Capture d’écran_2022-12-09_18-04-11](https://user-images.githubusercontent.com/72315006/206753862-1c5c616e-3c0c-4c9f-8f42-f7f5a7978c10.png)
![Capture d’écran_2022-12-21_22-08-40](https://user-images.githubusercontent.com/72315006/209003626-83729b00-6079-4653-a515-59d3f79cac0e.png)
![Capture d’écran_2022-12-22_06-28-37](https://user-images.githubusercontent.com/72315006/209063717-3c1cec6c-733b-469f-9f8a-623c534ab93b.png)

Frank Ward
-------

- [ ] Spawn
- [ ] Update Display Id

2940 Frank Ward Bird Trainer
Display_id is probably 428 as other humans pet trainer
https://db.thealphaproject.eu/index.php?action=show_creature&id=2940&filter=frank+ward&sort_order=name&pos=1&max=1

- wowpython:
0 -10156.5 1199.53 36.3752 4.34587

![Capture d’écran_2022-12-10_06-05-47](https://user-images.githubusercontent.com/72315006/206830221-36b75578-a3d8-4dba-b3ed-c713d6b11f81.png)

Hurom Juggendolf
----

- [ ] Spawn
- [ ] Update Display Id

2880 Hurom Juggendolf Boar Trainer
Probably use display_id 115

- mangos SDB:
0 -5619 -1529,399.757 0.934
- wowemu:
0 -5626.350098 -1539.589966 399.069000 3.131510
- wowpython:
0 -5610.18 -1546.11 399.798 6.13096
- wowpython:
0 -5626.35 -1539.59 399.069 3.13151

https://db.thealphaproject.eu/index.php?action=show_creature&id=2880&filter=hurom&sort_order=name&pos=1&max=1
![dsdds](https://user-images.githubusercontent.com/72315006/206831436-7b3e38ea-8c60-4c0b-87eb-83a77ddbd174.png)

Durdrek Karrin
---

- [ ] Spawn
- [ ] Update Display Id

2881 Durdrek Karrin Bear Trainer
Probably use display_id 115
https://db.thealphaproject.eu/index.php?action=show_creature&id=2881&filter=karrin&sort_order=name&pos=1&max=2
![unknocffdfwn](https://user-images.githubusercontent.com/72315006/206831415-8ab9860e-03f6-48fb-b6e8-396f7fa82eea.png)

Kyln Longclaw 
-----

- [ ] Spawn
- [ ] Update Subname

3697 Kyln Longclaw Boar Trainer
https://db.thealphaproject.eu/index.php?action=show_creature&id=3697&filter=kyln&sort_order=name&pos=1&max=1
![Capture d’écran_2022-12-10_06-05-32](https://user-images.githubusercontent.com/72315006/206830270-1b591c91-4f68-482a-a946-13925d23bdd9.png)

Whaldak Darkbenk
-----

- [ ] Update Display Id

2872 Waldak Darkbenk Spider trainer
Display_id is probably 428 as other humans/dwarf pet trainer of lock modan
https://db.thealphaproject.eu/index.php?action=show_creature&id=2872&filter=whaldak&sort_order=name&pos=1&max=1

![Capture d’écran_2022-12-10_06-06-06](https://user-images.githubusercontent.com/72315006/206830307-fc9c6582-4fd0-4c05-bf97-0f1dd2533bcd.png)

Lanie Reed
----

- [ ] Spawn
- [ ] Update Display Id

2941 Lanie Reed Spider Trainer
She should use display id 2585 like other females dwarf pet trainer.
From 0.5.5 WDB, need to be spawn to Eastvale logging camp (elwynn)

- wowemu:
0 -9456.990234 -1309.430054 45.045300 0.959931
- wowpython:
0 -9456.99 -1309.43 45.0453 0.959931

```
Entry: 1103 => Logging Camp
Name: Eldrin
Title: Tailor
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


Entry: 1975 => Logging Camp
Name: Eastvale Lumberjack
StaticFlags: 0
CreatureType: 7
CreatureFamily: 0


Entry: 2941 => ?
Name: Lanie Reed
Title: Spider Trainer
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


Entry: 5446 
Name: Tamed Spider
StaticFlags: 102
CreatureType: 1
CreatureFamily: 3


Entry: 1250 => Logging camp
Name: Drake Lindgren
Title: General & Trade Supplies
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


```

Kysandia
-----

- [ ] Spawn

https://db.thealphaproject.eu/index.php?action=show_creature&id=4153&filter=kysan&sort_order=name&pos=1&max=2
Located in Teldrassil

![Capture d’écran_2022-12-14_16-30-52](https://user-images.githubusercontent.com/72315006/207674589-4c662774-a3ad-43c5-b51d-8a1e45718596.png)

![Capture d’écran_2022-12-14_19-21-56](https://user-images.githubusercontent.com/72315006/207676911-bb837a48-a46d-42e7-bdda-4af2d4d2e684.png)

Talar
-----

- [ ] Spawn

4206 Talar Bear Trainer
https://db.thealphaproject.eu/index.php?action=show_creature&id=4206&filter=talar&sort_order=name&pos=2&max=2

![Capture d’écran_2022-12-15_22-03-46](https://user-images.githubusercontent.com/72315006/207966678-35a7d011-5b46-48b2-a3a9-f8e3d1798fc4.png)

Henria Derth
-------

- [ ] Spawn 

2870 Henriah Derth Wolf Trainer
Located Dun Morogh

https://crawler.thealphaproject.eu/search/Henria%20Derth
https://db.thealphaproject.eu/index.php?action=show_creature&id=2870&filter=Henria&sort_order=name&pos=1&max=1
![Capture d’écran_2022-12-19_04-49-34](https://user-images.githubusercontent.com/72315006/208344258-21c6333f-5792-46bf-bd27-9cff8f7e691e.png)

Bolyun
-------

- [ ] Spawn

Bolyun Spider Trainer
Located in Darnassus, probably at entrance near Fyrenna <Fruit Vendor>

https://db.thealphaproject.eu/index.php?action=show_creature&id=3698&filter=trainer&sort_order=name&pos=38&max=431

From WDB 3596 : All mobs around Bolyun are spwaned in Darnassus
![Bolyun WDB 3596](https://user-images.githubusercontent.com/72315006/208345979-c7011af0-233a-42c7-878b-bffd15ac964e.png)

Brogun
------

- [ ] Move to good position

5118 Brogun Stoneshield Boar Trainer
Located in IF

https://db.thealphaproject.eu/index.php?action=show_creature&id=5118&filter=brogun&sort_order=name&pos=1&max=1
![Capture d’écran_2022-12-20_15-09-27](https://user-images.githubusercontent.com/72315006/208686319-7c263b4b-4596-48d3-bae6-02076b6d8220.png)

Frank Lasson
-------

- [ ]  Update Name
- [ ] Update Subname
- [ ] Change Flag
- [ ] Update Display id

https://db.thealphaproject.eu/index.php?action=show_creature&id=4902&filter=4902&sort_order=name&pos=1&max=1
4902 Mikael Pierce should be Frank Lasson Spider Trainer
DIsplay id should be 428 for 0.5.3

![Capture d’écran_2022-12-21_21-31-43](https://user-images.githubusercontent.com/72315006/208998061-7e10ca31-6256-4c2e-8346-72df19c8c33a.png)

![Capture d’écran_2022-12-21_21-35-14](https://user-images.githubusercontent.com/72315006/208998375-e2231b87-cc55-4e8b-b64f-d2b1aa858b4a.png)

Kenna
-----

- [ ] Update Display Id
- [ ] Change name
- [ ] Change subname
- [ ] Update flag

https://db.thealphaproject.eu/index.php?action=show_creature&id=4901&filter=sara+pierce&sort_order=name&pos=1&max=1

4901 Sara pierce should be Kenna Larnad Crocilisk pet trainer
She should use display id 2585 like other females dwarf pet trainer.
She is already spawned at Thermore

![Capture d’écran_2022-12-21_21-58-38](https://user-images.githubusercontent.com/72315006/209001837-32e3e9c4-5499-4aff-bf4e-fd7cbda4792b.png)

Valyen
-----

- [ ] Spawn

4207 Valyen Nightsong Wolf Trainer
https://db.thealphaproject.eu/index.php?action=show_creature&id=4207&filter=valyen&sort_order=name&pos=2&max=2

![valyen](https://user-images.githubusercontent.com/72315006/209003761-6506200c-2a18-4f99-8cb0-2f3eaf3c4170.png)

Ransin
-----

- [ ] Change subname
- [ ] Update flag
- [ ] Update display id

2943 Ransin Crab Trainer
Probably located in IF (unsure)
He should use display_id 115 for 0.5.3

https://db.thealphaproject.eu/index.php?action=show_creature&id=2943&filter=ransin&sort_order=name&pos=1&max=1

![Capture d’écran_2022-12-21_22-05-20](https://user-images.githubusercontent.com/72315006/209004054-127d6029-e6fa-4f09-b35e-36b6941402e8.png)

Galthuk
-----

- [ ] Change subname
- [ ] Update flag
- [ ] Update display id

4043 Galthuk Bear Trainer
He should use display_id 1139
![Capture d’écran_2022-12-21_21-48-54](https://user-images.githubusercontent.com/72315006/209007464-268a1873-ea05-4a5d-ab35-194f904bc788.png)

https://db.thealphaproject.eu/index.php?action=show_creature&id=4043&filter=galth&sort_order=name&pos=2&max=2

Nerra
------

- [ ] Spawn

3899 Nerra Cat Trainer
Location Darnassus
https://db.thealphaproject.eu/index.php?action=show_creature&id=3699&filter=nerra&sort_order=name&pos=1&max=1

From WDB 3596
She should be spawn very close to Radnaal, we can see her between Nerra and Tamed cat
![Capture d’écran_2022-12-22_06-17-43](https://user-images.githubusercontent.com/72315006/209062487-187fe2f6-8f42-43f9-ab56-7e00e00d0f19.png)

**Comment by Daribon** [comment]
- 2876 Grunenstur Balindom
mangos:
-5267 -3059 344.055 2.604
wowemu:
-5256.109863 -3065.110107 342.787994 1.834390
wowpython:
-5256.11 -3065.11 342.788 1.83439

- 2941 Lanie Reed Spider Trainer
wowemu:
-9456.990234 -1309.430054 45.045300 0.959931
wowpython:
-9456.99 -1309.43 45.0453 0.959931

- 2880 Hurom Juggendolf Boar Trainer
mangos:
-5619 -1529,399.757 0.934
wowemu:
-5626.350098 -1539.589966 399.069000 3.131510
wowpython:
-5610.18 -1546.11 399.798 6.13096
wowpython:
-5626.35 -1539.59 399.069 3.13151

- 3689 Laer Stepperrunner Wolf Trainer
wowpython:
-2481.16 -473.534 -8.74122 4.88692

- 2940 Frank Ward Bird Trainer
wowpython:
-10156.5 1199.53 36.3752 4.34587

**Comment by geo-tp** [comment]
Frank Lasson
-------

- [ ] Move to good position (Durotar, no further infos)
- [ ]  Update Name
- [ ] Update Subname
- [ ] Change Flag
- [ ] Update Display id

https://db.thealphaproject.eu/index.php?action=show_creature&id=4902&filter=4902&sort_order=name&pos=1&max=1
4902 Mikael Pierce should be Frank Lasson Spider Trainer
DIsplay id should be 1139 for 0.5.3
Located In Durotar

![Capture d’écran_2022-12-21_21-31-43](https://user-images.githubusercontent.com/72315006/208998061-7e10ca31-6256-4c2e-8346-72df19c8c33a.png)

![Capture d’écran_2022-12-21_21-35-14](https://user-images.githubusercontent.com/72315006/208998375-e2231b87-cc55-4e8b-b64f-d2b1aa858b4a.png)
