### ISSUE TITLE
TODO: Stormwind Rework

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#822]
- [x] Change [General Marcus Jonathan](https://db.thealphaproject.eu/index.php?action=show_creature&id=466&filter=marcus&sort_order=name&pos=1&max=1)'s lvl to 95

**Source** from 0.5.5 (shot between 22-26/03/2004)
![33](https://user-images.githubusercontent.com/111394734/209483843-976fb141-28a9-4b55-939e-84760ef34d59.jpg)

- [x] Move Billy and Adam to the following coordinates:

[Billy](https://db.thealphaproject.eu/index.php?action=show_creature&id=1367&filter=billy&sort_order=name&pos=1&max=3):
Map: 0
Zone: 55
ADT: [48,30]
X: -8795.815
Y: 771.774
Z: 96.338
MapZ: 96.338
O: 1.691

[Adam](https://db.thealphaproject.eu/index.php?action=show_creature&id=1366&filter=adam&sort_order=name&pos=1&max=5):
Map: 0
Zone: 55
ADT: [48,30]
X: -8797.605
Y: 771.589
Z: 96.338
MapZ: 96.338
O: 1.510

**Source** from 0.5.5 (shot between 22-26/03/2004)
![39](https://user-images.githubusercontent.com/111394734/209484834-6fae03f8-89d6-4028-9975-c0b8d87e3143.jpg)

- [x] Relocate [Stockade Guards
](https://db.thealphaproject.eu/index.php?action=show_creature&id=4995&filter=Stockade&sort_order=name&pos=2&max=2)
**Guard 1** 
Spawn ID: 90454
Guid: 37212

Move Guard 1 to the following coordinates:
Map: 0
Zone: 55
ADT: [48,30]
X: -8785.008
Y: 826.591
Z: 97.650
MapZ: 97.650
O: 0.798

**Guard 2**
Spawn ID: 90456
Guid: 37214

Move Guard 2 to the follwoing coordinates:
Map: 0
Zone: 55
ADT: [48,30]
X: -8787.415
Y: 830.132
Z: 97.651
MapZ: 97.651
O: 0.767

**Guard 3**
Spawn ID: 90453
Guid: 37211

Move Guard 3 to the following coordinates:
Map: 0
Zone: 55
ADT: [48,30]
X: -8791.091
Y: 835.497
Z: 97.635
MapZ: 97.635
O: 0.272

**Guard 4**
Spawn ID: 90455
Guid: 37213

Change Guard 4's Display ID to 2989
Move Guard 4 to the following coordinates:
Map: 0
Zone: 55
ADT: [48,30]
X: -8782.847
Y: 826.419
Z: 97.411
MapZ: 97.411
O: 0.932

**Guard 5**

Spawn Guard 5 with DisplayID of 2989 on the following coordinates:
Map: 0
X: -8787.91
Y: 832.669
Z: 97.4384
O: 0.261799

**Source** 0.5.5 (shot between 22-26/03/2004)
![40](https://user-images.githubusercontent.com/111394734/209484637-1c387a7b-8070-4058-a32b-65f736ce6520.jpg)

I've planned it out to save as much effort changing Display IDs so I've just made a small rejig. Here's a visual of how it will look like:
![Guard Rotation](https://user-images.githubusercontent.com/111394734/209484775-0c9f657d-9505-473e-a287-80128f4311c6.png)
