### ISSUE TITLE
TODO: Coldridge Valley Rework

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#823]
- [ ] Change [Father Gavin](https://db.thealphaproject.eu/index.php?action=show_creature&id=1253&filter=gavin&sort_order=name&pos=2&max=3)'s level and faction

His LvL is supposed to be 15.
He should be friendly with the Alliance. Currently he is neutral and attackable by the alliance.

**Source** from 0.5.5 (shot between 22-26/03/2004)
![56](https://user-images.githubusercontent.com/111394734/209485159-f0756766-fe88-4955-8a8b-e55609e0e4ee.jpg)

- [ ] Change [Senir Whitebeard](https://db.thealphaproject.eu/index.php?action=show_creature&id=1252&filter=Senir&sort_order=name&pos=1&max=1)'s level to 9

**Source** from 0.5.5 (shot between 22-26/03/2004)
![59](https://user-images.githubusercontent.com/111394734/209485213-6488d45e-c3c6-425f-9391-e01cb16f38a3.jpg)

- [ ] Unequip [Ozzie Togglevolt](https://db.thealphaproject.eu/index.php?action=show_creature&id=1268&filter=ozzie&sort_order=name&pos=1&max=1)'s and [Razzle Spysprocket](https://db.thealphaproject.eu/index.php?action=show_creature&id=1269&filter=razzle&sort_order=name&pos=2&max=2)'s tools.

**Source** from 0.5.5 (shot between 22-26/03/2004)
![60](https://user-images.githubusercontent.com/111394734/209485272-918fac4a-9ab5-4f58-87ca-4eeb04dc600b.jpg)

- [ ] Change [Pilot Stonegear](https://db.thealphaproject.eu/index.php?action=show_creature&id=1377&filter=stonegear&sort_order=name&pos=1&max=1)'s DisplayID to 115, 312, 803, 824, 826 ,832, 1764, 2584 or 3232 (they're all the same)

**Source** from 0.5.5 (shot between 22-26/03/2004)
![67](https://user-images.githubusercontent.com/111394734/209486293-a99537e9-30f7-4fdb-bfc3-5fed0a65d85c.jpg)

**Comment by GrenderG** [comment]
Senir Whitebeard has a variable level (between 8 and 12). It's currently working as intended.
